### ISSUE TITLE
[description d'un signalement] Ajout d'un critère petit/gros point noir

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#102]
Ce critère permettra de différencier les signalements de problème des gros points noirs.

**Comment by julienfastre** [comment]
STocker les types dans une table séparée, faire une jointure entre les deux.

**Comment by julienfastre** [comment]
Je me suis dit que les petits et gros points noirs étaient, clairement, déterminés par la catégorie. Et que, donc, en cdonnaissant la catégorie on connaitrait si c'est un petit ou gros point noir. 

Je me suis donc dit qu'on pourrait modifier la base de donnée comme suit : 
- qu'il n'y ait pas plusieurs mais une seule catégorie par emplacement signalé (modifié la relation de many-to-many à many-to-one)
- créer une table avec les différents "types" de points noirs ;
- et relier cette table non pas au signalement lui-même, mais à la catégorie ;

Qu'en pensez-vous ?

**Comment by marcu** [comment]
ça me semble pas mal mais pour 
- qu'il n'y ait pas plusieurs mais une seule catégorie par emplacement signalé (modifié la relation de many-to-many à many-to-one)

pour moi, il vaut mieux garder cette relation many-to-many en attendant de voir comment ça va se passer : j'ai peur que cette classification ne soit pas la bonne et qu'une catégorie puisse aller dans différents types.

sinon la relation "types" - "catégorie" sera-t-elle une one-to-many?

**Comment by julienfastre** [comment]
Je pensais effectivement que la relation type-catégorie soit one-to-many. Autrement dit, les catégories ne seront reliées qu'à un seul type de signalement ("problème", "moyen terme" ou "point noir").

**Comment by marcu** [comment]
J'ai été confus dans le message précédent dsl. Je crois qu'il faut surtout avoir dans l'esprit que le **temps avance et donc qu'il faut prendre des décisions et s'y tenir**.
- **relation catégorie - emplacement**
  la relation catégorie - emplacement avait été décidée comme many-to-one. le code js respecte cette spécification et je crois que le symfony  aussi -> on ne change pas (en tout cas pour le 1er mars)
- **types (pouvant être "problème", "moyen terme" ou "point noir")** : 
  - soit on associe un type à un emplacement 
    - avantage : plus souple (à Mons une rue récemment refaite a comme pbm  "Accumulation d’eau en cas de pluie", pour résoudre le problème il faut refaire la rue... c'est donc un gros point noir alors que cette catégorie me fait plus penser à petit ou moyen point noir)
    - options d'affichage (sur la carte) : on peut choisir le type et les catégories
  - soit on associe un type à une categorie
    - options d'affichage (sur la carte) : on peut choisir les catégories vu que le type est fixé en fct de la catégorie

Pour moi l'option "associe un type à un emplacement" est la meilleure. Elle peut-être comprise comme les catégories permettent d'ordonner / structurer les points noirs, les types permettent de savoir comment se fait la gestion du point noir. Mais Julien si tu as déjà codé l'autre version autan la garder pour qu'on avance.

**Comment by julienfastre** [comment]
Ok. De toute façon je ne comptais pas changer ça pour le 5 mars :-)

Ceci dit il y a une position intermédiaire :
- on associe un type (donc gros/petit/moyen point noir) aux catégories ;
- on associe également un type à un emplacement ;

Et, à chaque fois qu'un nouvel emplacement est créé, le système regarde les catégories. S'il n'y a qu'une seule catégorie associée à l'emplacement, ou si toutes les catégories sont associée au même type (donc toutes des catégories "petits problèmes", par exemple), alors le système détermine le type **de l'emplacement** du même type que la catégorie. (Et si ça n'est pas le cas (donc s'il y a des catégories de différents types), il faudra choisir un critère pour décider du type de l'emplacement... à discuter par la suite).

Ca nous permettra également de filtrer les catégories puis les emplacements par public (public vélo, moto, chaisard, etc.) si on ajoute une caractéristique "public" par type.

**Comment by julienfastre** [comment]
Il reste à faire : 
- [x] traçabilité des changements dans la base de données
- [x] qui peut changer (pour l'instant tout le monde peut modifier ce paramètre... oups :-1: 
- [x] mettre à jour la documentation

Mais le critère petit/gros apparait dans les réponses en json.

**Comment by julienfastre** [comment]
Voilà, c'est fait...

**Comment by marcu** [comment]
on le voit dans la requête json?

**Comment by julienfastre** [comment]
Oui. J'ai mis à jour la documentation.
