### ISSUE TITLE
Champ numéro de téléphone + json

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#107]

**Comment by julienfastre** [comment]
Heu... je ne comprends pas trop...

**Comment by marcu** [comment]
c'est pour moi : je dois adapter la requête JSON.

Au fait quel est le champ attendu dans la requête JSON pour l'ajout d'un nouveau point noir?

**Comment by julienfastre** [comment]
Le script côté serveur s'attend à recevoir du string. Pour une
validation plus précise, on verra plus tard :-).

**Comment by marcu** [comment]
oui mais l'intitulé de la string :)
