### ISSUE TITLE
le label lors d'une réponse json lors d'un login est vide

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#108]
lors du login "admin" sur la page du choix des villes, le json renvoyé est le suivant :

{"entity":"user","id":5,"label":"","nbComment":0,"nbVote":0,"roles":{"0":"ROLE_ADMIN","1":"ROLE_NOTATION","2":"ROLE_CATEGORY","3":"ROLE_DETAILS_LITTLE","4":"ROLE_SEE_USER_DETAILS","8":"ROLE_PUBLISHED","10":"ROLE_MANAGER_ALTER","11":"ROLE_USER"}

le label est vide -> pas d'affichage du label dans la barre "menu" noire en haut.

**Comment by julienfastre** [comment]
ok, vu.
