### ISSUE TITLE
back-end

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#11]
Est-ce qu'une gestion « back-end » vous permet par exemple d'ajouter des commentaires, de gérer le suivi du point noir, à qui il a été signalé, etc ?

parc Maxime de liège 

---

marc: pas compris

**Comment by julienfastre** [comment]
Oui, il y a une interface de gestion pour les administrateurs: supprimer un point, modifier des coordonnées, etc. 

Ceci dit, je me demande si on aurait pas intérêt, pour plus de simplicité, à faire tout en 'front-end': si l'utilisateur est enregistré ET administrateur, les boutons "supprimer" ou "modifier ce point" apparaissent; ils n'apparaissent pas s'il ne l'est pas. Qu'en pensez-vous ?

**Comment by julienfastre** [comment]
Est-on d'accord pour dire que tout se modifie dans le "front-end" ? Je peux fermer cette issue ?

**Comment by marcu** [comment]
ok pour moi
