### ISSUE TITLE
action d'édition d'un point par moderator/manager: afficher la description du point avant le formulaire d'édition

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#112]
Lorsqu'un modérateur, un manager ou un administrateur clique sur un point, c'est le formulaire d'édition qui s'affiche. Ils ne voient pas les photos et l'affichage comme les autres utilisateurs. 

Je trouve que c'est dommage parce que la présentation du point est jolie :-) 

Je propose donc que ce soit cette présentation qui s'affiche et, en bas, un lien "éditer". Si un modérateur/manager veut modifier un point, il devrait cliquer sur ce lien pour afficher le formulaire d'édition.

Qu'en pensez-vous ?

**Comment by marcu** [comment]
le système de la 1.1 va être entre les deux...

**Comment by julienfastre** [comment]
ha ok, je ne savais pas ce que tu avais prévu... On en rediscutera après alors.
