### ISSUE TITLE
[description json] renommer "accepted" en "published" (?)

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#113]
Dans la description json d'une place, faut-il renommer "accepted" en "published" pour indiquer l'état de publication d'un emplacement ? 

Cela donnerait donc : 

``` json
{ 
    "entity":"place",
    /*.... */
    "published":true //plutôt que "accepted"
}
```

Ca serait plus cohérent:
- avec le champ: le champ ne signifie plus le refus ou l'acceptation mais l'état de publication ;
- avec les autres parties du système (le rôle qui donne le droit de modifier ce champ est ROLE_PUBLISHED)

ON le fait ? pas d'implication dans le javascript ?

**Comment by marcu** [comment]
ça me va, si tu le fais il faut changer js/main.js ligne 161. merci

**Comment by julienfastre** [comment]
Vu la discussion de la #122 , il n'y a pas lieu de changer 'accepted' en "published".
