### ISSUE TITLE
avoir la liste des différents groupes qui côtent pour une ville

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#119]

**Comment by julienfastre** [comment]
En fait, il est possible d'utiliser la requête `wikipedale_group_covers_zone` (soit `/groups/bytype/bycovering/{type}.{slugZone}.{_format}`) avec tous les groupes qui ont le rôle notation, soit `manager`, `moderator` et `notation` pour le moment. Il faut envoyer trois requêtes mais, pour le moment, ça fait le boulot. 

En attendant, pour le moment, on a que les `moderator` qui utilisent des couleurs... on a personne d'autre de prévu à très court terme... (mais bon, je me méfie du court terme)
