### ISSUE TITLE
nom de domaine pour l'outil

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#12]
Est-ce qu'un nom de domaine spécifique est prévu pour le lancement officiel et pour la visibilité de l'application ?

---

par Maxime de liège

**Comment by marcu** [comment]
quel nom de domaine? faut en trouver un simple et accrocheur!

**Comment by julienfastre** [comment]
Quelques idées pour le nom de domaine : 
- traduire des mots vers l'espéranto : 
  belaurbo (belle ville), biciklo (vélo), bela biciklo (beau vélo)
- autres idées
  veloteur.be , velomaville, ...

wikpedale.be et pointsnoirs.be est également disponible. Mais pour le premier, on me fait remarquer que 'wiki' est mis à toutes les sauces, et que 'pédale' n'est pas du plus bel effet. 

D'autres idées ?

**Comment by marcu** [comment]
- http://www.cyclette.be
- http://www.mapcy.be
- http://www.mapcyc.be
- http://www.velup.be/
- http://www.cyclup.be
- http://www.cyclop.be
- http://www.ameliovelo.be
- http://www.velocipede.be/

**Comment by julienfastre** [comment]
Pour moi :

cyclette.be +1
mapcy +0.5
velup +0.5
ameliovelo +0.75
velocipede -0.5

**Comment by marcu** [comment]
- une proposition d'un membre de la locale : OGPONEL pour Outil de Gestion (c'est plus exact que seulement "signalisation") des POints Noirs

que fait-on une liste de proposition qu'on envoie à des connaissances et on voit un peu le retour?

**Comment by julienfastre** [comment]
OGPONEL, je trouve ça un peu impersonnel. 

OK pour ta proposition. J'en ai déjà un peu parlé autour de moi. Il faudrait faire un mail un peu structuré.
