### ISSUE TITLE
retour des données d'un signalement en json lorsqu'il a été modifé

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#121]
@julienfastre est-ce possible?

**Comment by julienfastre** [comment]
En fait le script effectue un renvoi http par un code http 301 vers l'url qui permet de récupérer les données de l'emplacement en json (c'est recommandé pour éviter l'usage du bouton "actualiser" qui renvoie un formulaire) (voir aussi ici http://fr.m.wikipedia.org/wiki/Liste_des_codes_HTTP ) . Il n'est pas possible pour toi de le suivre en javascript?

( j'ai remarqué tout à l'heure que le js ne suivait pas le code http de redirection... Je pensais que ça le faisait)

**Comment by julienfastre** [comment]
Pardon, c'est un code 302. Et je vois bien la réponse avec le json de l'emplacement tel que modifié dans Firebug après une requete sur change.json.

**Comment by marcu** [comment]
oui dsl je suis vraiment stressé et je vais trop vite sur certains problèmes
