### ISSUE TITLE
L'endroit n'a pas été trouvé dans la base de donnée

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#122]
après une requête de délétion du genre : 

{"entity":"place","id":"438","accepted":false}

, l'erreur suivante est renvoyée :

L'endroit n'a pas été trouvé dans la base de donnée

**Comment by julienfastre** [comment]
En fait, c'est la requête de réponse qui refuse d'envoyer des emplacements qui ne sont pas "accepted". J'étais parti du principe que personne ne pourrait les voir. 

La solution ? Créer un rôle spécifique qui permet de voir les places non acceptées.

Ce qui me vient à la considération suivante : il faudrait peut-être les deux critères "accepted" et "published" : 
- accepted (boolean) pour les places acceptées ou pas. Une place peut être refusée parce qu'elle a été introduite en double, parce qu'elle est fantaisiste (ne correspond pas au vélo, etc.), parce que son auteur n'a jamais confirmé son adresse de courriel, etc.
- published (boolean) comme raccourci pour éviter les charges sur la base de donnée sur les emplacements résolus depuis plus d'un an, etc. (ou alors retourner à une requete qui vérifie les jointures, ce qui est peut-être une solution plus propre, finalement). 

Qu'en pensez-vous ?

**Comment by marcu** [comment]
pour moi ça ne vaut pas la peine de faire la différence entre accepted et published avec les définitions que tu proposes

as tu pris en compte les signalement qui ont été proposés et dont le mail n'a pas été vérifié?

**Comment by julienfastre** [comment]
Ok. On filtrera les signalements résolus depuis plus d'un an par une requête ad hoc au moment où... ça sera possible (faut que j'adapte la BD).
