### ISSUE TITLE
option d'affichage selon la couleur 

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#123]

**Comment by marcu** [comment]
je le mets pour la 1.2 car ça me semble pas si prioritaire (qu'en dis tu @julienfastre  ?)

**Comment by julienfastre** [comment]
Oki!

Je pense qu'il est bon de geler le développement de certaines fonctionnalités jusqu'au 5, histoire que tout fonctionne.

Envoyé depuis mon téléphone

Ducobu Marc notifications@github.com a écrit :
