### ISSUE TITLE
avoir les managers pour une ville via le twig (comme pour les categories)

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#126]
est-ce possible?

lorsqu'il est changé, puis je seulement renvoyer l'id du nouveau manager?

**Comment by julienfastre** [comment]
Même remarque que pour le #127 : je ne sais pas quoi en faire dans le template homepage, j'ai complété la doc...

La doc pour les groupes est ici : http://doc.wikipedale.fastre.info/class-Progracqteur.WikipedaleBundle.Entity.Management.Group.html

**Comment by marcu** [comment]
le problème est que je ne peux pas mettre le code suivant : 

``` twig
<select style="width:100%" data-placeholder="" id="blop">
{% for mng in managers %}
   <option value="{{mng.id}}">{{mng.label}}</option>
{% endfor %}
</select>
```

il lance l'exception "Method "label" for object "Progracqteur\WikipedaleBundle\Entity\Management\Group" does not exist in ProgracqteurWikipedaleBundle:Default:map.html.twig at line 21"

**Comment by julienfastre** [comment]
Ha oui zut j'y avais pas pensé... la classe `Group` est une classe enfant de la classe `BaseGroup` de FOSUserBundle, et la méthode n'est pas `getLabel()` mais `getName()`. Comme la classe parente est dans un autre bundle, la doc n'a pas été générée... 

Je vais voir si je ne peux pas corriger ça. 

En attendant, il suffit de changer `mng.label` en `mng.name`...

``` twig
<select style="width:100%" data-placeholder="" id="blop">
{% for mng in managers %}
   <option value="{{mng.id}}">{{mng.name}}</option>
{% endfor %}
</select>
```

**Comment by marcu** [comment]
parfait ça me suffit
