### ISSUE TITLE
avoir les différents types ("points_noirs", "moyen terme", "petits problèmes"... ) pour une ville via le twig (comme pour les categories)

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#127]
merci

**Comment by julienfastre** [comment]
Je ne savais pas où metter le placetype dans le template twig. J'ai donc [ajouté des commentaires au template homepage.html.twig](https://github.com/progracqteur/WikiPedale/blob/master/src/Progracqteur/WikipedaleBundle/Resources/views/Default/homepage.html.twig#L7)

Pour rappel, la documentation des classes est sur le net (je l'ai remise à jour aujourd'hui). La doc de la classe placetype est ici : http://doc.wikipedale.fastre.info/class-Progracqteur.WikipedaleBundle.Entity.Model.Place.PlaceType.html

Ainsi, pour avoir le label d'un placetype (donc utiliser la fonction `getLabel()` de la classe), il suffit de faire `<nom de la variable qui contient le place type>.label`, par exemple : 

``` twig
{% for placetype in placeTypes %}

<option value="{{placetype.id}}">{{placetype.label}}</option>

{% endfor %}
```

**Comment by marcu** [comment]
merci
