### ISSUE TITLE
qd l'utilisateur se logge il faut actualiser l'ensemble des données des signalements en cache

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#128]
sinon si on passe d'utilisateur normal à admin on ne peut pas voir les données perso d'un signaleur

**Comment by marcu** [comment]
déplacement dans la 1.2

il faut vérifier si les données du coté js sont tjs en accord avec le serveur : 
- mettre "addUserInfo: true" dans les requêtes json
- lancer update_markers_and_associated_data si les données "users" ont été modifiées

**Comment by julienfastre** [comment]
Est-ce que c'est résolu ? Ca en est où ?
