### ISSUE TITLE
Mettre en place algorithme de classification de point noirs (était: placetype peut-il être vide?)

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#129]
actuellement lors d'un ajout d'une nouvelle place il est vide.

**Comment by julienfastre** [comment]
Très bonne question. Je dirais non. 

Je pense qu'il faut que l'on ait un placetype associé aux catégories, et que le signalement prenne le placetype des catégories auxquelles il est associé. 

Seul problème: quand on a plusieurs catégories...

Solution imaginée : 
- n'avoir qu'une seule catégorie par emplacement (je pense que ça va nous gêner pour les points noirs, pour les "petits problèmes" il n'y aura pas de... problème :-) 
- avoir un ordre de priorité entre les types: le système choisira celui qui sera le plus prioritaire (le type "petit problème" sera peut-être plus prioritaire, parce que résolvable plus facilement). 
- ne pouvoir associer que des catégories du même type à l'emplacement (avec vérification par l'UI)

**Comment by marcu** [comment]
cette solution me semble bien : avoir un ordre de priorité entre les types: le système choisira celui qui sera le plus prioritaire (le type "petit problème" sera peut-être plus prioritaire, parce que résolvable plus facilement)

de toute façon on permet par la suite de modifier le placetype, du coup ce n'est pas très grâve. si c'est fort gênant on peut adapter le comportement.

**Comment by julienfastre** [comment]
L'attribution du type ne se ferait plus par objet mais serait intégré dans le processus de gestion des signalements. Cette issue est donc devenue sans objet.
