### ISSUE TITLE
lors de l'ajout montrer les points noirs qui existent déjà (éviter doublons)

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#13]
Lorsqu'on choisit « signaler un point noir », la carte proposée est vierge, il serait plus pratique de disposer des points existants, pour ne pas ajouter un point qui existerait déjà.

et

Si le système est maintenu tel quel, on doit alors chercher au préalable si le point noir est déjà encodé, ce qui nous amène à zoomer et déplacer la carte. Ne pourrait-on pas conserver ce zoom et positionnement lorsqu'on clique pour signaler le point qui n'y serait pas encore ? Actuellement, on tombe sur une carte dé-zoomée et il faut chercher à nouveau le lieu précis.

par maxime de liège

---

marc: à faire mais pas prioritaire

**Comment by julienfastre** [comment]
Proposition de solution : que les points noirs qui existent déjà sur la carte devraient apparaitre avec une opacité moins forte. Est-ce que ça donne quelque chose ?

**Comment by julienfastre** [comment]
je pense que c'est fait aussi...
