### ISSUE TITLE
numéro de téléphone obligatoire

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#132]
actuellement si on met un numéro de téléphone vide ou même un fixe (9 chiffres) il y a une erreur de validation.

pour moi le numéro de téléphone doit être optionnel. qu'en pensez-vous? que fait-on? il faut que le code js ai la même attente que le backend.

**Comment by julienfastre** [comment]
Actuellement, il faut en effet que le numéro de téléphone ait entre 10 et 15 caractères (espaces compris).

Je pense qu'on devrait abaisser la validation de 9 à 20 chiffres (ainsi on pourrait avoir des +32 12 345 67 89 et il nous resterait une certaine marge). 

Ou alors, on met juste un minimum de une lettre et un maximum de 255 caractères et puis tant pis...

**Comment by marcu** [comment]
il vaut mieux laisser la possibilité à l'utilisateur de ne pas mettre de numéro : si il ne veut pas en mettre un, il mettre qqchose de bidon qui peut être embêtant. pour moi le numéro c'est un plus, pas une obligation.

**Comment by julienfastre** [comment]
ok. Je vais adapter la validation.

Julien

**Comment by julienfastre** [comment]
Fait depuis b5b5947c76205e27125867acbc55c8c18c54d55d . 

Il faut juste que le numéro soit "notnull".
