### ISSUE TITLE
requête json pour changer le manager

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#133]
la requête json suivante n'est pas prise en compte pour sauvearder le manager : 

{"entity":"place","id":"26","manager": {"entity":"group","type":"MANAGER","id":"4"}}

**Comment by julienfastre** [comment]
Voilà, j'ai corrigé par 3327c52ab484e9bf0b73ddbda3ffba839d2dab4c.

Note pour plus tard : il est possible que la modification du "type" du signalement pose également problème. Il faudra que je corrige la fonction `setType()` dans la classe `Place` de la même manière.
