### ISSUE TITLE
mettre à jour les données pour l'affichage categories & types lors de la modification d'un point noir

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#134]
afin que les options d'affichage marchent pour le point noir dans l'état après la mod et non avant.

**Comment by marcu** [comment]
trouver où se trouve l'élem avec indexOf puis le supprimer avec pop(i) où i est l'index retourné par indexOf

**Comment by julienfastre** [comment]
Est-ce que ceci n'est pas terminé ? On ne pourrait pas fermer l'issue ?
