### ISSUE TITLE
comment savoir qui peut modifier la note du cem?

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#136]
faut-il que la personne aie : 
- le rôle "notationt"
- avoir aussi un group "moderator" ayant comme notation "cem"?

si oui j'ai l'impression que l'info sur les groups n'est pas tjs renvoyé par json par exemple pour "web/app_dev.php/place/list/bycity.json?city=MONS&addUserInfo=true"

**Comment by julienfastre** [comment]
Il faut avoir : 
- le role notation : ROLE_NOTATION (c'est toujours le cas lorsque la personne appartient au groupe MANAGER ou MODERATOR) ;
- la notation "cem" (c'est toujours le cas lorsque le groupe est MODERATOR ou MANAGER) ;
- modifier un point qui est dans la zone du groupe MODERATOR ou MANAGER de l'utilisateur connecté.
