### ISSUE TITLE
addUserInfo doit se comporter sur le même modèle que authenticate.json 

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#137]
sinon le cem ne peut modifier une couleur.

**Comment by julienfastre** [comment]
Ceci dit, il sera plus facile de modifier le comportement avec la version 2.2 de Symfony : la fonction "normalize" de l'interface "Normalizer" a une variable "context"... (enfin, c'est un peu compliqué à expliquer par écrit...)

**Comment by marcu** [comment]
faudra supprimer les commentaires de la fonction normalize de UserNormalizer.php
