### ISSUE TITLE
se rappeler de moi à la prochaine visite

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#142]
Pbm pour rajouter le bouton "se rappeler de moi à la prochaine visite".

Lors du login je fais une requête ajax sur "wikipedale_authenticate" mais je ne sais pas ce que je dois mettre afin de dire que l'utilisateur veut qu'on "se rappelle de lui à la prochaine visite"?

**Comment by julienfastre** [comment]
Je mets ça en 1.2.
