### ISSUE TITLE
Edition qd admin ne marche plus

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#143]
Sous firefox comme le lien "<a id="span_place_description_loc_button" style="display: span; width:100px;" onclick="javascript:descriptionEditOrSave('loc');"></a>" est vide, logo d'édition n'est pas affiché même qd loggé en "admin"

**Comment by nondidju** [comment]
Dans le fichier main.js, il faut remplacer les éléments de type:
$(e).text('Editer') 
& $(e).text('Sauver')

par img src=" {{asset('img/edit.png')}} " title=" {{ 'Controls.edit'|trans({}, 'pointMessages') }} "
& img src=" {{asset('img/save.png')}} " title=" {{ 'Controls.save'|trans({}, 'pointMessages') }} "

Ce fichier regorge de textes destinés à être affichés (tels "éditer", "sauver", etc). Il faut systématiquement faire appel aux fichiers *.fr.yml pour y insérer les textes.

**Comment by julienfastre** [comment]
Attention que le fichier JS n'est pas interprété par du PHP : les traductions ne sont donc pas affichées dans le fichier main.js. 

Les solutions ? 
- créer un fichier .js qui contiendrait toutes les traductions, et qui serait créé par php à la demande. Exemple : 

``` javascript
var intl_save = "Sauver";
var int_delete = "Supprimer";
var intl_edit = "Editer";
```

(en symfony/twig, ce fichier serait le suivant : 

``` twig
var intl_edit= "{{ 'Controls.edit'|trans({}, 'pointMessages') }}"
```

Les variables seraient appelées dans main.js : 

``` javascript
$(e).text(int_edit); 
```
- autre solution que j'imagine: utiliser une bibliothèque qui gère l'i10n et l'i18n. Pour mon autre projet j'utilise AngularJs et je trouve que ça fait un très bon boulot... Pas encore testé l'i10n.

Il y a peut-être d'autres bibliothèques disponibles en jquery.
- il y a peut-être d'autres solutions, mais je ne les vois pas...

**Comment by marcu** [comment]
une autre solution est d'avoir les deux images générées dans le twig et d'en afficher soit l'une soit l'autre en fct du cas.
