### ISSUE TITLE
Affichage pour les visiteurs/non-loggué/usagers normaux VS affichage pour les CeM/Admin

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#144]
Pour résumer
- les visiteurs veulent une grande carte pour explorer
- les CeM veulent une grande zone édition

Je viens de faire 2 essais de changement de mode.
- le premier (cliquer sur le texte "Changer la taille de la carte") change la taille de la carte et la taille de la zone édition
- le second (cliquer sur le texte "Test mode CeM") supprime la carte et n'affiche de la zone édition (avec la mini-carte dedans)

Que pensez-vous des solutions? Mais dites-vous bien que ce sont des prototypes et donc tout n'est donc pas fonctionnel (je sais que la carte ne se centre pas sur le point, ...) D'autres idées?

**Comment by julienfastre** [comment]
Je préfère nettement la première "changer la taille de la carte". Je trouve que c'est vraiment trop petit en mode "cem". 

Je trouve qu'il faudrait que graphiquement ça soit joli: une icone bien compréhensible plutôt qu'un texte. 

Je mets la question en 1.2.

**Comment by marcu** [comment]
La taille de la carte peut-être agrandie (comme le niveau de zoom, la taille des pointeurs). Si c'est juste ça qui te dérange ça peut-être adapté sans pbm.

Le texte est là à titre provisoire. Il faut trouver l'endroit idéal où mettre le bouton (en fonction du comportement qu'on adopte).

Une possibilité peut aussi être de laisser les deux comportements.

**Comment by nondidju** [comment]
Ne pourrait-on pas avoir, par défaut, la grande carte (70% carte / 30% infos) avec un bouton en bas de la colonne de droite pour basculer vers la vue "test mode CEM"? Cette vue afficherait plus d'infos sur le point en question, comme les commentaires (d'ailleurs le texte du bouton pourrait être "voir les commentaires").
