### ISSUE TITLE
l'admin ne peut pas modifier "moderatorComment"

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#146]
A ce propos y a t il un droit bien spécial? Ou on peut se contenter du droit permettant de modifier la couleur/status "CeM"?

**Comment by julienfastre** [comment]
Ha oui j'ai oublié de l'ajouter à l'admin; mais le CeM a bien les droits !

**Comment by julienfastre** [comment]
Pour moi, il ne faut pas non plus donner tous les droits aux admin :) 

Ca complique également la vérification des droits:  un admin n'est pas lié à une zone. Il faut donc faire deux tests lorsqu'un utilisateur modifie qqch: soit il est admin, soit il appartient à un groupe compétent géographiquement pour cette zone. 

Réduire les droits de l'admin est plus simple (et l'admin peut se mettre dans plusieurs groupes s'il le souhaite).
