### ISSUE TITLE
[formulaire d'ajout] adapter le bouton "ajotuer un point" au contexte

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#149]
Le bouton "ajouter un point" reste identique lorsqu'on a cliqué dessus. 

![Capture du 2013-04-15 21:26:59](https://f.cloud.github.com/assets/345600/382826/7a95695e-a602-11e2-8eb2-c2cc2968f675.png)

Je pense que dans une version antérieure il devenait "annuler" quand le formulaire d'ajout était ouvert. J'aimais bien ce changement.

**Comment by marcu** [comment]
done - voir commit avec #148
