### ISSUE TITLE
[formulaire d'ajout] placeholders du formulaire

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#151]
Pour moi, les placeholder des formulaires ne devraient pas contenir des exemples mais des textes qui éclairent la saisie. 

Je propose que l'on fasse les changements suivants : 
- téléphone => "Un numéro où vous joindre" ;
- localisation => "Rue et numéro"

Qu'en pensez-vous ?

**Comment by marcu** [comment]
Done + aussi champ email + simplification du mail
