### ISSUE TITLE
nom de lieu -> zoom dans carte

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#16]
On devrait pouvoir ajuster la carte en écrivant l'adresse dans le champ « lieu » pour éviter de zoomer, chercher, se repérer (comme une recherche sur google map ou openstreet dans ce cas)

par maxime de liège

---

marc:

bonne idée mais voir comment le faire car qd clique sur la carte l'adresse doit aussi se mettre automatiquement...

**Comment by julienfastre** [comment]
Je pense que, dans l'interface graphique, il pourrait y avoir un champ pour faire une recherche par adresse. Comme sur la page d'accueil d'openstreetmap ou de googlemap. 

Après, l'utilisateur n'aurait qu'à cliquer à l'endroit exact du signalement.

**Comment by marcu** [comment]
oui je vois bien ça :
- si il tape dans le champ lieu une adresse il peut cliquer sur un bouton nommé "zoom" et la carte ce center sur ce lieu (appeler le bouton autrement serait bien mais pas d'idée)
- si il clique à un endroit alors le champ lieu se rempli automatiquement (si il n'a pas encore été édité)

de plus je me demande ne faut-t-il pas faire l'ajout des points noirs sur la page d'index?
- genre un bouton en haut à droite dans la carte nommé "ajouter un point noir"
- quand on clique dessus la carte se met en mode ajout :
  - le bouton change en "retour au mode exploration"
  - on voit les points noirs qui existent déjà (peut-t-on encore cliquer dessus?)
  - quand on clique sur la carte un formulaire arrive et on peut ajouter le point noir
  - quand on clique sur "retour au mode exploration" on retour à ce qui se faisait au début

Qu'en pensez-vous?

On peut aussi penser de faire la même chose pour le mode "gestion quand l'utilisateur est connecté" mais il faut que certaines données ne soient renvoyées en json que quand l'utilisateur est administrateur (genre le mail de contact). Je crois donc qu'il faut quand l'utilisateur est connecté qu'il soit redirigé (sans le savoir sur /mons/gestion et que cette page fasse la bonne requête json).

**Comment by julienfastre** [comment]
Que fait-on de cette idée ? on n'en a plus parlé.

**Comment by marcu** [comment]
mis à 1.5 si on a le temps pas prioritaire du tout
