### ISSUE TITLE
Commentaire du gestionnaire de voirie

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#169]
Espace où le gestionnaire de voirie peut ajouter un commentaire public

**Comment by julienfastre** [comment]
Je ne pense pas que ça soit une idée à implémenter pour le moment. Lors de la dernière réunion à laquelle j'ai assisté, j'ai demandé si un commentaire "gestionnaire de voirie" était à prévoir et on m'a répondu non. Donc je préfère que l'on pose la question à la prochaine réunion le 15/06.

**Comment by marcu** [comment]
La demande vient du CeM de Mons qui est le gars qui va utiliser l'outil. Il dit que ça va lui éviter de faire le messager du gestionnaire de voirie. Moi ça me semble tout à fait justifié et intéressant. Je crois qu'on doit en priorité écouter les utilisateurs plutôt que les gens qui ne vont pas et n'utilisent pas l'outil.

**Comment by julienfastre** [comment]
En même temps on ne peut pas aller "contre" notre comité d'accompagnement. Parce qu'il est tout à fait possible que les gestionnaires de voiries disent "ha, nous, non, on ne veut pas introduire quelque chose directement on a trop de boulot aussi". On ferait quoi, alors, nous ?

Je pense que tu pourrais dire au Cem de Mons qu'on en tient bien compte et qu'on en reparle à cette réunion de juin. On garde l'issue ouverte, on la place en 1.5 et on attend de voir. Ok ?
