### ISSUE TITLE
long / lat gps

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#17]
On pourrait également prévoir d'encoder directement les longitude et latitude pour les cyclistes qui utilisent un GPS.

par maxime de liège

---

marc: c'est possible. mettre les champs lon/lat en visible dans le formulaire?

**Comment by julienfastre** [comment]
Moi je ne suis pas pour mettre les champs lon/lat visibles dans le formulaire : c'est pas joli et ça fait "geek".

Il pourrait y avoir une option: soit cliquer sur la carte, soit entrer à la main. 

Ceci dit, à mon avis, peu de gens vont utiliser cette option s'il y a une carte. C'est pas si facile que ça d'utiliser un gps et de relever les coordonnées d'un point.

**Comment by julienfastre** [comment]
Peut-on fermer cette issue ?
