### ISSUE TITLE
Bouton "ne plus afficher ce signalement" visible que pour l'admin

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#170]

**Comment by marcu** [comment]
Dans le code JS l'affichage du bouton se fait si l'utilisateur a le rôle 'ROLE_PUBLISHED' et il me semble que les CeM l'ont. Du coup soit on oublie ce rôle (et j'affiche le bouton que pour les admins), soit on ne donne plus ce rôle aux CeM. Qu'en dis tu @julienfastre ?

**Comment by julienfastre** [comment]
Je n'ai pas vraiment d'avis. On peut enlever le rôle à tout le monde dans un premier temps, histoire de rester en cohérence entre les rôles et l'UI, et de ne pas dé-coder quelque chose, puis voir pour la suite.

**Comment by marcu** [comment]
Oui ça me semble bien. Mais je ne vois pas comment le faire via l'admin.
