### ISSUE TITLE
[affichage d'un point]Erreur affichage adresses email

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#172]
Je fais la manip suivante : 
1. aller sur la page d'accueil ;
2. aller sur la page "mons" ;
3. regarder un point ;
4. se connecter avec un compte "cem" ;

Et les adresses mails du créteur s'affiche comme ça : 

![erreur d'affichage adresse mail](https://f.cloud.github.com/assets/345600/544643/00fcfaee-c254-11e2-9e42-ac29ebb3180f.png)

Mais si je recharge la page, tout va bien...

J'attends avec de "pousser" les modifications de @marcu dans la branche stable: je me dis que les CEM n'auront pas le réflexe de recharger la page.

**Comment by marcu** [comment]
@julienfastre je n'arrive pas à reproduire le bug. Quel est l'id du signalement? Es-tu sur google chrome?

**Comment by julienfastre** [comment]
J'arrive à reproduire le problème sous chrome et firefox, sous ubuntu :-(

Bon courage...
