### ISSUE TITLE
application iphone/android

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#18]
Tant qu'à faire, une petite application ou version simplifiée pour les Iphone -et autres horreurs technologiques- qui pourraient encoder rapidement un point noir en prenant une photo du lieu concerné avec relevé de la position GPS ?

par maxime de liège

---

c'est un travail de fou. pour éviter ça on peut essayer de rendre le siteweb beau et fonctionnable pour iphone android (utiliser jquery mobile et open layers mobile).

ou faire un siteweb simplifié sur lequel la personne qui navigue depuis un mobile est redirigée.

**Comment by julienfastre** [comment]
A mon avis il faudra ouvrir un autre projet pour cela. 

Pas sûr que cela soit si fou que ça... En tout cas ça pourrait être bien pratique et "faire la différence" avec d'autres projets existants.

**Comment by julienfastre** [comment]
Un autre projet devra être ouvert; mais il faudra tenir compte de la possibilité lors du développement.
