### ISSUE TITLE
ajout web service voies lentes

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#198]
Ajout du web services "voies lentes". 

Le web service est une couche WMS à ajouter à la carte (http://dev.openlayers.org/docs/files/OpenLayers/Layer/WMS-js.html#OpenLayers.Layer.WMS.OpenLayers.Layer.WMS). Deux couches sont à ajouter : 
- Itinéraires locaux
- Voies lentes

Dans deux couches que l'on peut activer/désactiver.

Attention qu'il y aura peut-être des problèmes de reprojection... Le service web de la RW est en projection WGS84 (EPSG:4326) et en Lambert Belge (EPSG:31370), la notre est en Google Mercator (EPSG:900913). Je ne sais pas si une reprojection est possible à la volée par OpenLayers.

**Comment by nondidju** [comment]
J'ai l'impression qu'on aurait plus à y gagner en utilisant le fond de carte d'OpenCycleMap (ou autre si un autre projet destiné aux cyclistes voit le jour). C'est l'occasion de demander l'autorisation au SPW pour utiliser cette source afin d'améliorer OSM. Non?
