### ISSUE TITLE
système de tags

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#20]
Il serait intéressant, si on ajoute les précisions quant au point noir encodé, de permettre une navigation photographique filtrée sur base de ces critères, tout comme un filtre d'affichage des points sur la carte (par exemple uniquement les bordures, ou uniquement les SUL demandés, etc)

par maxime de liège

---

marc : oui ça peut -être une bonne idée. je ne crois pas qu'il fasse le faire comme dans le formulaire du siteweb du gracq c'est à dire un formulaire fixe. je verrai bien un système de tag (on peut mettre plusieurs tags sur un point noir, rajouter un tag qui n'est pas dans la liste grobale des tags,...)

**Comment by julienfastre** [comment]
J'applique un label 'question': parce que je trouve, personnellement, qu'il faudrait encore penser cette fonction. Ne sera-ce pas trop dur à gérer si les utilisateurs ajoutent des dizaines de tags ?

**Comment by marcu** [comment]
ce genre de chose est tjs dure à prévoir. le mieux est de tester.

**Comment by julienfastre** [comment]
Report à la 1.5: ne me semble pas prioritaire.
