### ISSUE TITLE
transmettre les données orangeade -> nouveau système

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#21]
Est-ce que les points noirs déjà communiqués par la passé vont être encodés dans la nouvelle carte ?

par marxime de liège

---

marc : OUI, sinon c'est se foutre de la gueule des autres.

**Comment by julienfastre** [comment]
fait :-)

**Comment by julienfastre** [comment]
Je réouvre l'issue: j'ai oublié d'importer les couleurs...

**Comment by julienfastre** [comment]
Voilà, je pense que c'est bon maintenant: j'ai transféré les couleurs selon le schéma suivant : 

``` php
$status_new_value = null;
            switch($old_place->couleur)
            {
                case 'red' : $status_new_value = 1;
                    break;
                case 'green' : $status_new_value = 3;
                    break;
                case 'white' : $status_new_value = null;
                    break;
                case 'yellow' : $status_new_value = 2;
                    break;
            }
```

Dites moi si c'est ok.

**Comment by marcu** [comment]
je crois que c'est bon.

On 20 November 2012 22:33, Julien Fastré notifications@github.com wrote:

> Voilà, je pense que c'est bon maintenant: j'ai transféré les couleurs
> selon le schéma suivant :
> 
> $status_new_value = null;
>             switch($old_place->couleur)
>             {
>                 case 'red' : $status_new_value = 1;
>                     break;
>                 case 'green' : $status_new_value = 3;
>                     break;
>                 case 'white' : $status_new_value = null;
>                     break;
>                 case 'yellow' : $status_new_value = 2;
>                     break;
>             }
> 
> Dites moi si c'est ok.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/progracqteur/WikiPedale/issues/21#issuecomment-10574093.

## 

et en avant pour de folles aventures...
