### ISSUE TITLE
Email manager contenant un lien pour signaler que le pbm a été réglé

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#222]
le manager pourra ne plus devoir se logger sur uello

**Comment by julienfastre** [comment]
L'action "un problème a été réglé" : 
- ajoutera un "commentaire privé" qui dit "l'utilisateur XYZ a signalé que le problème est réglé"
- enverra un email vers les modérateurs

Mais cela ne modifiera pas le statut de l'emplacement automatiquement: ça me semble être une faille de sécurité.

**Comment by marcu** [comment]
ok
