### ISSUE TITLE
Lien d'accès direct aux fiches de signalement (sans login/password) contenu dans chaque courriel de notification.

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#223]
Pour simplifier l’accès direct aux fiches de signalement, un lien (sans login/password) sera ajouté dans chaque courriel de notification.

Identique que la #222 ?

**Comment by julienfastre** [comment]
Voir mon commentaire sur la #222: pour moi il ne faut pas pouvoir modifier un signalement sans authentification. Imaginons que la personne transfère le courriel: le correspondant pourrait introduire une modification seule, sans login/mot de passe !

Je propose de fermer cette issue.

**Comment by marcu** [comment]
je suis d'accord mais c'est aussi dans le pv. on justifira.
