### ISSUE TITLE
Export CSV

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#224]
On va programmer un export au format CSV de listes (filtrées) de signalements, avec les champs les plus utiles (pour les gestionnaires de voirie uniquement).

**Comment by julienfastre** [comment]
L'export CSV est prêt côté serveur.

Il faudrait ajouter un lien vers le fichier `/place/list/bycity.csv?city=MONS` (même que JSON, en remplaçant json par csv) dans l'UI.

Il n'y a pas de possibilité de filtres plus précis pour le moment.

**Comment by julienfastre** [comment]
Tout est dans la branche `add_csv_export` et pas encore dans la branche master, ni stable.

La branche add_csv_export est basée sur 'place.add_term` donc il faut d'abord régler add_term (me suis un peu planté :-( .

**Comment by marcu** [comment]
Mail de luc le 21 Nov : tenir compte des filtres appliqués.
