### ISSUE TITLE
[sécurité] qui peut modifier quoi, dans les emplacements

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#30]
Pour la gestion des emplacements, je me dis que seules certaines catégories d'utilisateurs doivent pouvoir modifer certaines éléments. 

Petite proposition : 

Différentes catégories d'utilisateurs, du celui qui a le plus de pouvoir à celui qui en a le moins. Un administrateur a donc tous les droits des personnes qui sont "sous" lui, plus ceux qui appartiennent à son étage.
1. les administrateurs du site ; 
2. les personnes en lien avec les associations cyclistes  OU les personnes en lien avec une municipalité ; 
3. les visiteurs enregistrés ;
4. les visiteurs non-enregistrés/ anonymes

Les droits de chacun sur les emplacements : 
- Créer un emplacement : à partir de visiteur enregistrés
- Modification de  geom (emplacement géographique) : à partir de 'visiteurs enregistrés' 
- Ajout de commentaire, vote : tout visiteur, même anonyme peut ajouter un vote ou un commentaire 
- Modification de l'adresse: à partir de 'visiteurs enregistrés' 
- Modification de la description : à partir de 'visiteurs enregistrés'
- Ajout de photo : à partir de 'visiteurs enregistrés'  (plutôt pour la sécurité du serveur que pour des raisons internes au système)
- Modification de statusBicycle: à partir de 'utilisateurs en lien avec les associations cyclistes' 
- Modification de statusCity: à partir de 'utilisateurs en lien avec les communes/municipalités' 
- Supprimer un emplacement: à partir de 'administrateurs'

**Comment by marcu** [comment]
Pour moi : 
- créer un emplacement : tout visiteur, même anonyme (j'aime pas trop les sites internet où il faut faire plein d'étapes d'inscription avant de pouvoir faire ce que je veux - souvent je m'en vais avant). Après il peut y avoir une modération sur ce qui a été ajouté.

**Comment by julienfastre** [comment]
En effet, je suis d'accord, c'était une coquille, j'aurai dû écrire "visiteurs non-enregistrés", mais le "non-" est resté dans le clavier.

**Comment by julienfastre** [comment]
Un service spécifique a été mis en place db923c11197f022bcd8883e57340926287a12031  et suivants.
