### ISSUE TITLE
avoir accès aux données user via json

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#35]
a-t-on besoin d'avoir cette donnée à chaque réponse json? Il faut surtout savoir qd l'utilisateur n'est plus connecté alors qu'il l'était (afin de l'informer).

**Comment by julienfastre** [comment]
Peut-être que cette information n'est pas nécessaire pour tous les clients. Peut-être devrait-on alors ajouter un paramètre GET dans les requêtes JSON qui indiquerait s'il faut ajouter les données de l'utilisateur.

La requête serait alors : /place/change.json?addUserInfo=true .

Si je comprends bien également, il faudra ajouter un champ 'role' dans la normalisation JSON d'un objet user, ceux qui ont été définis dans l'issue #30.

**Comment by marcu** [comment]
non autan tout faire en json ça me semble plus simple.

oui ça me semble bien d'avoir un role pour l'utilisateur.

**Comment by julienfastre** [comment]
Le paramètre addUserInfo a été pris en compte sur toutes les requêtes qui renvoient du JSON. 

Il ne reste plus qu'à afficher l'adresse mail de l'utilisateur dans ce cas.

A voir si ça sera encore nécessaire avec l'utilisateur de l'authentification par WSSE.
