### ISSUE TITLE
Associer des couleurs aux places

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#37]
Comment fait-on? Quel système? On avait parlé une couleur pour la commune et une pour le gracq?

**Comment by julienfastre** [comment]
Moi je propose :

0 (dans la base de donnée) => non pris en compte => blanc
1 => pris en compte remis (pour le gracq), et en voie de résolution (par la Ville) => orange
2 => résolu => vert

Qu'en pensez-vous ?

**Comment by marcu** [comment]
Donc le gracq peut  :
- accepter un point noir
- dire si un point noir est résolut
  la ville peut :
- dire que le point noir est pris en considération et en voie de résolution (dans ce cas là on peut penser à ce que la ville donne une date)

Sinon je crois que c'est important de faire la différence entre :
rejetter un point noir (le gracq le trouve pas important) et un point noir qui n'a pas encore été analysé.

Donc :
0 -> pas analysé ( blanc )
-1 -> rejetté ( gris )
1 -> pris en compte par le gracq ( rouge )
2 -> en voie de résolution par la ville (orange )
3 -> résolu (vert )

Ici la gestion des couleurs est mélée entre la ville et le gracq. Ne faut-il pas donner à chacun une gestion de la couleur.

Il faut aussi penser à :
- la ville peut ne pas participer
- le gracq peut ne pas participer
- un autre organisme ou personne physique peut participer

Peut-être le plus simple est de garder ce système de couleur MAIS de pouvoir dire (en fonction des cas ) :
qui gère les différents passage de couleurs.

On pourrait alors avoir par exemple :
- Collaboration ville et gracq :
  0 -> (1 ou -1 ou 3 ) ; gracq 
  1 -> 2 : ville 
  2 -> 3 gracq

Ville sans gracq mais mr bidule gère l'outil :
0 -> (1 ou -1 ou 3 ) ; mr bidule 
1 -> 2 : ville 
2 -> 3 mr bidule

Ville ne collabore pas :
0 -> (1 ou -1 ou 3 ) : gracq 
1 -> 2 : gracq
2 -> 3 : gracq

**Comment by julienfastre** [comment]
Le système que tu proposes me convient, mais il est différent de ce que j'avais imaginé. 

J'avais imaginé que la ville et le gracq gèrent les statuts chacun dans leur coin. La ville pourrait dire qu'un emplacement est résolu, mais le gracq pas encore. On aurait eu alors deux couleurs dans les emplacements; et les logo auraient été séparés en deux (coté gauche, la ville; coté droit, le gracq - ou vice-versa). 

Maintenant, n'est-ce pas trop manichéen comme système ? Je n'en sais rien.

Techniquement, pour passer à la proposition ci-dessus, il faudra enlever un champ dans la classe place, la base de donnée, et la normalisation json, mais ça n'est vraiment pas compliqué.

**Comment by julienfastre** [comment]
Je relance ce sujet... A mon avis, c'est une des fonctionnalités les plus importantes à ré-insérer pour pouvoir passer "en production". 

En résumé, la question est: faut-il une notation qui mélange les avis du GRACQ et de la Ville, ou une notation qui sépare les deux avis. 

Pour ma part, je suis pour la séparation. Pourquoi? parce que je pense qu'il y a beaucoup de différence dans les avis des cyclistes et de la Ville. Et qu'imposer une négociation entre les deux est peut-être problématique.

**Comment by marcu** [comment]
OK. Attaquons nous à ça!

Peut-être pour être vraiment général on peut ne pas limiter les couleurs à la ville et au gracq mais à un nombre paramétrisable d'utilisateurs?

On peut aussi à la place de mettre 3 couleur faire un dégradé du rouge au vert...

**Comment by julienfastre** [comment]
Pour le dégradé, je suis pas trop fan: ça ne me semble pas être très lisible. A mon avis, ceux qui ont des problèmes pour distinguer les couleurs ne vont pas s'y retrouver. 

Je ne comprends pas "le nombre paramétrisable d'utilisateurs".

**Comment by julienfastre** [comment]
Il a donc été décidé :
- de créer une notation séparée et adaptée pour plusieurs acteurs. La gestion de la notation doit être dynamique. Il pourra y en avoir une pour la ville, une pour le gracq, une pour le fietserbond, etc. Sans que cela soit défini à l'avance.
- pour chaque notation, il y aura cinq niveaux, de -1 à 4: 
  - 0 pour 'non traité' (blanc)
  - -1 pour 'rejeté' (gris)
  - 1 pour 'pris en compte' (rouge)
  - 2 pour 'en cours de résolution' (orange)
  - 3 pour 'résolu' (vert)
- chaque acteur pourra choisir lui-même les niveaux qu'il utilise (peu probable que le gracq utilise le niveau 2, par exemple). 
- les droits des utilisateurs seront gérés par commune: un utilisateur pourra avoir les droits pour modifier la notation 'ville' uniquement pour la ville où il est actif, par exemple.
- graphiquement, les marques sur la carte seront séparées en fonction des différentes notations: les ronds pourront être séparés en deux, voire trois morceaux. Ceci dit, dans un premier temps, nous allons nous limiter à deux notations possibles, pour éviter de devoir générer une infinité d'images.

**Comment by nondidju** [comment]
Gérer des couleurs sur les pointeurs en fonction de tous ces états me semble fort compliqué. Ne pourrait-on pas ajouter un champs "État" dans le panneau détails d'un point noir avec plusieurs possibilités ?
- Non traité à l'heure actuelle
- Rejeté par ... (assoc partenaire GRACQ, Gamah,..)
- Pris en compte et soutenu par le GRACQ
- Pris en compte par ... (Ville, Région, Province,...)
- Proposition soumise par ... (Ville, Région, Province,...)
- Proposition soumise par ... (assoc partenaire GRACQ, Gamah,..)
- La proposition adoptée est reconnue satisfaisante par la communauté (votes supérieurs à 7/10)
- La proposition adoptée est reconnue satisfaisante par ... (assoc partenaire GRACQ, Gamah,..)
- La réalisation de l'aménagement est reconnue satisfaisante par la communauté (votes supérieurs à 7/10)
- La réalisation de l'aménagement est reconnue satisfaisante par ... (assoc partenaire GRACQ, Gamah,..)

Ceci s'accompagnerait d'un système plus complexe qui prévoit pour chaque point noir, la liste de plusieurs solutions. Chaque solution pouvant être commentée, votée,...comme le système http://brainstorm.ubuntu.com

Si un tel système ne pourrait pas être opérationnel pour la version 1.0, je serais d'avis d'attendre qu'il le soit avant de mettre cette fonctionnalité en place.

**Comment by julienfastre** [comment]
Pour plus de clarté, je pense qu'il faut un "état" par association qui utilise le système (GRACQ, Ville, Région, etc.). Et que l' "état" qu'ils donnent à l'emplacement soit clairement séparé. 

Pour le "proposition soumise par...": ce seront toujours les citoyens qui soumettront leurs propositions.

J'aime bien que l'on voie les couleurs sur la carte. Mais c'est vrai qu'avoir trois couleurs pour un emplacement, ça fait beaucoup... 

Et si on regroupait les "états" par groupes: un groupe "associations" et un groupe "gestionnaires de voirie". Si plusieurs assoc' donne un "état" à un signalement, on fait la moyenne, et c'est cette moyenne (arrondie) qui s'affiche du côté gauche du pointeur. Du côté droit s'affichera la moyenne "gestionnaires de voiries" (à mon avis on n'aura qu'un seul intervenant de ce côté-là, la moyenne sera vite faite! )

**Comment by marcu** [comment]
Moi aussi je suis attaché aux couleurs.

Je ne suis pas sûr qu'il faille penser tout de suis à faire des groupes car je ne suis pas sûr que le problème va se poser. Pourquoi ne pas attendre de voir ce qui se passe... Va t on vraiment arriver un jour à  2 associations / la ville / la région sur un même point noir?

**Comment by nondidju** [comment]
Conservons les couleurs proposées ci-dessus, mais évitons d'embrouiller ceux qui ne le seraient pas encore assez en affichant une légende définissant ces couleurs (celle-ci pourrait par contre se retrouver dans l'aide). Je propose par contre une combinaison avec ma proposition qui explicite ces couleurs.

Voici donc le champs état d'un point noir :
[pointeur blanc] Non-traité
[pointeur rejeté] Rejeté. Voir explications.
[pointeur vert] Résolu (si < 70%, voir ci-dessous)
ou [pointeur orange] En cours... (si > 70%)

...
- [avatar utilisateur] Solution 1 proposée par l'auteur de l'énoncé
- [Logo GRACQ] Solution 2 proposée par le GRACQ
- [Logo ville] Solution 3 proposée par le gestionnaire de voirie

Résolution du problème en cours : [---------------........](moyenne des 3 ci-dessous ; si < 70%, pointeur vert)
Détails : Communauté : 75% - Associations : 60% - Gestionnaire de voirie : 100%

PS : Est-il possible de changer l'apparence des pointeurs ? Je peux en redessiner de plus jolis... Voir si le futur logo ne pourrait pas se décliner ainsi.

**Comment by julienfastre** [comment]
@nondidju je ne comprends pas...

**Comment by marcu** [comment]
De ce que je comprends, Benoit veut que chaque utilisateur gérant un point noir puisse indiquer le pourcentage de résolution (de 1 à 100). Quand on affiche le point, on fait un calcul avec toutes les gaduations de tous les utilisateurs impliqués et en fonction du résultat le point est soit rouge soit orange soit vert....

Le vert pour >70% me semble étrange. Pour moi c'est résolu quand c'est à 100%. Puis la graduation me semble compliquée à expliquer et à comprendre. Ca me semble plus simple les 3 propositions : "rien de fait", "en résolution", "résolu". De si on a une échelle de 1 à 100, il faut faire varier le chiffre et donc on demande à l'utilisateur de se loger souvent...

Oui on peut modifier les pointeurs, ceux qui se trouvent actuellement sont pour un test (il ne sont pas beau, pas symétriques). Ils se trouvent dans web/openlayers/img, mais avant de choisir les pointeurs finaux il faut se mettre d'accord sur l'affichage des couleurs.

**Comment by julienfastre** [comment]
@nondidju est-ce bien ce que Marc explique ? 

Je préfère également une logique de "pris en compte", "pas pris en compte", "solution prévue", "solution réalisée, point résolu" à une échelle qui n'est pas "fermée"  ( @marcu il y a un terme mathématique pour ça, non ? ). Ca me semble plus proche de la réalité.

**Comment by marcu** [comment]
Quels sont les couleurs différentes?
"statusBicycle"
"statusCity"

Ca m'aiderai d'avoir la liste des couleurs qui sont données. Ou alors d'avoir tjs des status et de mettre -2 quand non utilisés.

Qui gère la variable "accepted"? Signifie-il -1?

Que contient la variable "statuses"?

---

pour la question mathématique je dirai "finie"...

**Comment by julienfastre** [comment]
J'ai mis à jour la documentation : https://github.com/progracqteur/WikiPedale/wiki/Structure-des-r%C3%A9ponses-en-JSON

La variable "accepted" signifie que l'emplacement est publié. Si on a un problème avec un emplacement et qu'on veut le faire disparaitre, c'est cette valeur qu'il faut placer sur false: l'emplacement est toujours dans la base de donnée, mais n'apparait plus sur aucun résultat.

**Comment by marcu** [comment]
pour colorer les marqueurs, il faut un ordre. quelle convention prend on? en fonction de l'ordre d'apparance dans statuses ou ordre alphabétique ou une variable en plus?

**Comment by julienfastre** [comment]
Heu... je ne comprends pas... pourquoi un ordre ?

**Comment by marcu** [comment]
La variable "statuses" ne contient pas tout le temps des éléments ; si rien n'est donné je considèrerai la couleur comme blanc.

Il faut aussi pouvoir savoir pour une ville donnée combien de couleurs peuvent-être affichées.

**Comment by julienfastre** [comment]
J'avais imaginé ça de la même manière: s'il n'y a aucun statuses, la couleur du marqueur est blanche.

**Comment by marcu** [comment]
Mais il reste tjs : 
- pour une ville donnée, savoir combien de couleurs peuvent-être affichées
- ordre pour afficher les couleurs

**Comment by julienfastre** [comment]
On peut imaginer une requête qui indique le nombre de statuses utilisés par ville. Ca te serait utile ? 

Est-ce que ça doit être une information disponible de manière asynchrone ou qui soit disponible dans le script "homepage.html.twig" ?

Pour l'ordre, aucune idée. Je pense qu'il faut un ordre fixe qui soit toujours le même de ville en ville.

**Comment by marcu** [comment]
Dans le script homepage.html.twig ça me semble bien.

J'aurai dit plutôt un ordre qui puisse être paramétré par les gens qui gèrent la ville mais ce n'est pas très important.

**Comment by julienfastre** [comment]
ok.

**Comment by marcu** [comment]
mais vu le mail de luc on met ce point en pause

**Comment by julienfastre** [comment]
Oui je pense qu'il faut définir un document global avant de décider.

**Comment by julienfastre** [comment]
Concernant les rôles et les couleurs : les groupes de type "Modérateur" (=Conseiller en mobilité) DOIVENT avoir accès uniquement au status de type "cem". Leur "couleur" est donc visible dans le statut de type "cem".

Autrement dit, pour récupérer la couleur, il faut voir dans cette partie du json : 

``` json
{
  "id" : 0,
  "entity":"place",
  /* etc... */
  "statuses":[
      {"t":"cem","v":2}, //la couleur du CEM est ici !
      {"t":"SPW","v":3} //ceci n'est pas la couleur du CEM. NORMALEMENT si c'est un petit point noir (=un signalement) il ne devrait pas y avoir d'autre couleurs
  ]
}
```
