### ISSUE TITLE
Accès au répertoire web via js

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#41]
Si je vais sur http://localhost:8888/WikiPedale//web/app_dev.php les marqueurs sont bien affichés sur la carte (dans le js l'url pour trouver les marqueurs est http://localhost:8888/WikiPedale//OpenLayers/img/marker.png)
Si je vais sur http://localhost:8888/WikiPedale//web/app_dev.php/ les marqueurs sont pas affichés sur la carte (dans le js l'url pour trouver les marqueurs est http://localhost:8888/WikiPedale//web/app_dev.php/OpenLayers/img/marker.png)

Comment faire pour rendre ça uniforme? Est-ce possible avec "FOSJsRoutingBundle"?

**Comment by julienfastre** [comment]
As-tu essayé d'utiliser `Routing.getBaseUrl() + '/' + "chemin vers l'image"` ? 

Il y a des doubles slashes (//) dans tes chemins: est-ce normal ?

**Comment by marcu** [comment]
Cool je vais essayer au soir. Oui, je ne sais pas trop comment ça se fait (à mon avis ça va être géré via Routing).

**Comment by marcu** [comment]
Ca m'a un peu aidé mais le code n'est pas très propre car
Routing.getBaseUrl() retourne /Wikipedale//web/app.dev et je voudrais avoir /Wikipedale//web/

var baseUrlsplit = Routing.getBaseUrl().split('/');
var web_dir = ''
for (i = 0; i < (baseUrlsplit.length - 1); i++)
{
    web_dir = web_dir + baseUrlsplit[i] + '/';
} 
var img_url = web_dir + 'OpenLayers/img/'; // where is the dir containing the OpenLayers images

**Comment by julienfastre** [comment]
Effectivement, c'est pas très propre. 

je vais chercher dans la doc de fosJsRoutingBundle, voir s'il n'existe pas un autre moyen. Sinon je leur suggérerai de créer une fonction ad hoc...

**Comment by marcu** [comment]
même si le code n'est pas beau ça marche -> femré
