### ISSUE TITLE
Correction de la licence OSM

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#47]
OSM est maintenant sous licence ODbL, plus sous licence CC-BY-SA. 

voir ici : http://www.openstreetmap.org/copyright/en (la version française n'est pas encore à jour)

**Comment by marcu** [comment]
et il faut changer qqchose?

**Comment by julienfastre** [comment]
Je pense qu'il faut que la licence soit "Data from OpenStreetmap contributors - ODbL Licence" ou un truc du genre.

**Comment by nondidju** [comment]
J'indiquerais : "Données cartographiques : contributeurs OpenStreetMap".
"contributeurs OpenStreetMap" étant lié à la page http://www.openstreetmap.org/copyright

J'imagine qu'une prochaine version d'OpenLayers fera une adaptation de ce style.

**Comment by julienfastre** [comment]
Oui, c'est vrai, il est possible que la prochaine version de OpenLayers remette à jour les mentions...

**Comment by marcu** [comment]
J'ai mis à jour OpenLayers (2.12). La version 2.12 ne prend pas encore ce changement de license. Du coup j'ai un peu modifé à la main.
