### ISSUE TITLE
Format des dates en json

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#48]
Pour l'instant, les dates sont transformées en JSON dans un format "par défaut" qui est le suivant : 

`{"date":"2012-10-02 00:19:52","timezone_type":3,"timezone":"Europe\/Berlin"}`

Ce format vous convient-il ? 

Une autre possibilité serait d'ajouter, ou de ne garder qu'un timestamp unix. On perdrait cependant des informations sur le fuseau horaire. 

Ca serait donc : `{"date":"2012-10-02 00:19:52","timezone_type":3,"timezone":"Europe\/Berlin","unix":1256336542333}` 

ou...

 `{,"unix":1256336542333,"entity":datetime}`

Que faire ?

**Comment by marcu** [comment]
timestamp!

**Comment by julienfastre** [comment]
ok

**Comment by julienfastre** [comment]
fait : 737d200998fd89d73694e84c0a7a34549e7c73fe
