### ISSUE TITLE
[idée] toujours laisser le nom de la ville dans l'URL

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#5]
comme ça quand les gens partagent les liens c'est plus facile (enfin c'est une idée - à en discuter)

**Comment by julienfastre** [comment]
Deux remarques : 

### Au niveau pratique:

Donc, on aurait, 
- /mons/place/list/bycity.json (il n'est prévu qu'un retour de JSON)
- /mons/gestion.html (pour la gestion)
- /mons pour la page d'accueil, sur mons (l'url resterait sur /mons, il ne s'agirait pas d'une redirection)

Par contre je vois difficilement l'intérêt pour : 
- /mons/place/view/8.json ou /mons/place/view/8.html
- /mons/place/list/bybbox.json (je vais garder la recherche par bbox, d'abord parce qu'elle est créée, ensuite parce que je pense que je vais la garder pour l'application android que je suis en train d'imaginer)
- /mons/photo/new.html (page spéciale pour ajouter une photo) 

Qu'en pensez-vous ? Etes-vous d'accord de ne le mettre que là où c'est pertinent ? Ou faut-il le mettre partout ? (ça demanderait de dédoubler le fichier de routing, d'où l'intérêt de se limiter, voir remarque suivante)

Autre remarque:

A mon avis, il faut dédoubler les url pour ceux qui n'ont pas choisi de ville au préalable. Par exemple, /gestion doit continuer à exister, de même que la homepage / .

Etes-vous ok aussi ?

### Au niveau technique:

Quand un paramètre "city" sera découvert, il sera comparé avec celui stocké dans les paramètres de session.
- Si le paramètre n'existe pas dans la session, alors il sera ajouté
- S'il est le même, alors rien ne se passe ;
- S'il est différent, alors il est changé.

Les changements nécessiteront une requête dans la BD, d'où l'idée de filtrer les changements. 

Etes-vous d'accord avec le fait de récupérer le paramètre "city" dans la session plutot qu'ailleurs (c'est le sens de mes explications)....

**Comment by marcu** [comment]
### URL

Oui tu as raison Julien, il ne faut pas laisser le nom de la ville dans l'URL partout. Je crois qu'il faut juste le mettre pour les pages d'accueil. Donc :
- /mons -> page d'accueil de Mons
- /mons/gestion -> page de gestion de Mons
- / -> page d'accueil avec choix de ville
- /gestion -> page d'accueil gestion avec choix de ville
- /place/list/bycity.json?city=mons -> liste des points noirs en json
- /place/view/8.json ou /place/view/8.html -> voir un point noir en particulier et fichier json
- /place/list/bybbox.json  -> liste des points noirs en json d'une bbox
- /photo/id_photo/ -> page de gestion de la photo ayant l'id "id_photo". dans cette page on peut voir toutes les photos déja existante et en rajouter une

### Au niveau technique:

Quand un paramètre "city" sera découvert, il sera comparé avec celui stocké dans les paramètres de session.
- Si le paramètre n'existe pas dans la session, alors il sera ajouté
- S'il est le même, alors rien ne se passe ;
- S'il est différent, alors il est changé. -> j'ai pas compris lequel tu veux changer. moi je crois que l'URL doit être plus fort que la session. les gens vont être fou si ils vont sur mons/gestion et qu'ils voient la page de liège.

### Utilisation des sessions

Si je te comprends bien Julien, tu veux mettre les données dans la session afin de ne pas faire des requètes sql. J'aurai plutôt traité le problème de cette manière : avoir un tableau dans un fichier de config dont les clés sont les noms de ville et contenant les valeurs que nous avons besoin et donc pour accéder à la longitude de la ville on ne ferai plus $_SESSION['lon_ville'] mais data['nom_ville']['longitude'] ou un truc du genre. Je trouve ça plus direct car les données des sessions sont stockées sur le serveur. A vrai dire, ça ne change pas grand chose et puis je ne connais pas bien symfony et twig, c'est peut-être plus compliqué de cette manière.

**Comment by julienfastre** [comment]
Ca me semble plus simple et plus pratique de faire une requête SQL la première fois qu'on renseigne la ville de l'utilisateur, et de stocker le résultat dans la session pour les fois suivantes. 
- Les requêtes SQL sont plus rapides que la recherche dans un fichier pour ce nombre de données (la Wallonie, c'est 262 communes, et si on ne se relie pas directement au GRACQ, on ne peut pas se contenter des communes où une locale du GRACQ est active), et autant penser notre système pour qu'il soit réutilisable ailleurs, dans des endroits où il y a plus que 262 communes;
- il n'y aura qu'une requête SQL au moment de la création ou du changement de "ville" par un visiteur, après les données seront sérialisées dans les données de session
- apache gère tout seul la destruction des données de sessions devenus inutiles
- le fichier contenant les données de session est de toute manière lu à chaque requête

**Comment by julienfastre** [comment]
Citation d'un message précédent : 
- /mons -> page d'accueil de Mons
- /mons/gestion -> page de gestion de Mons
- / -> page d'accueil avec choix de ville
- /gestion -> page d'accueil gestion avec choix de ville
- /place/list/bycity.json?city=mons -> liste des points noirs en json
- /place/view/8.json ou /place/view/8.html -> voir un point noir en particulier et fichier json
- /place/list/bybbox.json  -> liste des points noirs en json d'une bbox
- /photo/id_photo/ -> page de gestion de la photo ayant l'id "id_photo". dans cette page on peut voir toutes les photos déja existante et en rajouter une

C'est fait, non ?
