### ISSUE TITLE
Représentation graphique des votes

### ISSUE THREAD

**Issue by nondidju** [progracqteur/WikiPedale#51]
J'ai créé 5 fichiers images représentant des étoiles de 1 à 5 (répertoire web/img). Mon idée est de représenter le nombre de votes par ces images de cette manière :

<img src=\"..img/stars0' + nbVote + '.png\" />
où "nbVote" représente le chiffre de 1 à 5 reçu pour créer un lien du type stars01.png, stars02.png, stars03.png,...

Cependant je n'arrive pas à générer ce code, ni dans les fichiers html.twig, ni dans les javascript. 

Marc, pourrais-tu regarder dans les fichiers .js pour insérer quelque chose du genre ?

Merci.

**Comment by julienfastre** [comment]
Je ne comprends pas. (même si apparemment je ne suis pas concerné...)

**Comment by nondidju** [comment]
Le code présent dans cette demande n'a pas été affiché, ce qui complique sa compréhension.

Actuellement, le site affiche pour un point : 3 votes
J'aimerais représenter ceci par l'image ***-- (3 étoiles pleines, 2 vides. Pour autant que les votes soient de 1 à 5)
Avec donc un code du style src="stars3.png" où 3 est défini par le chiffre affiché.

**Comment by marcu** [comment]
On avait pensé à nbVote comme le nombre de personnes qui ont voté pour le points noir ou le commentaire (chaque personne peut faire un +1). Du coup l'image n'est pas adaptée.

J'imagine que tu as pensé que chaque utilisateur puisse voter de 1 à 5 pour chaque point noir.

Il faut en discuter et accorder nos violons (skype?)

**Comment by nondidju** [comment]
Ah, je n'avais pas compris ça comme ça. Il faut alors 2 données : la moyenne des votes et le nombre des votes (qui est intéressante pour évaluer la pertinence du pourcentage obtenu). Après ça, il faudrait un algorithme jouant sur les 2 données pour afficher les points les plus populaires...

Un skype oui... demain après-midi ? 13h ?

**Comment by julienfastre** [comment]
Ok, Benoit, j'intégrerai ça dans le JSON qui est renvoyé mais... les votes ne sont pas du tout implémentés pour le moment ! voir #26

**Comment by marcu** [comment]
Ce n'est pas plus simple d'avoir un système "+1" et "-1" à la http://stackoverflow.com/

**Comment by julienfastre** [comment]
Je me demande, en effet, si ça n'est pas plus simple à gérer . 

Là, on va attribuer des étoiles à des éléments... que l'on voudrait voir disparaitre ! Pas tout à fait le concept même de l'attribution de mérite... 

On pourrait faire deux actions différentes, également: 
- un bouton "je suis d'accord avec le signament" pour les problèmes ;
- un vote avec des étoiles, des chiffres, ou des préférences, pour les solutions. 

Ou alors c'est trop compliqué ?

**Comment by nondidju** [comment]
C'est bien ainsi mais le vote pour le signalement devrait plutôt signifier "je trouve que ce problème est important". Les désaccords sur la description du problème se régleront via les commentaires.

Techniquement, on peut donc avancer sur cette solution.

**Comment by julienfastre** [comment]
Puis-je clore ce fil et que l'on suive l'implémentation du vote dans le fil #26 ? 

(Vous rouvrirez si vous n'êtes pas d'accord :-) )

**Comment by marcu** [comment]
ok pour moi.
