### ISSUE TITLE
Ajout de photo quand non logé

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#52]

**Comment by nondidju** [comment]
Il faut vraiment limiter les fonctionnalités d'un compte non-connecté. Je serais même d'avis de ne pas permettre la création de point sans être connecté mais je peux comprendre le frein que ça peut représenter... Pour les photos par contre, je n'en vois pas vraiment pas l'intérêt. Il vaut mieux encourager à la création de compte qui seront plus faciles à gérer.

**Comment by marcu** [comment]
Pourquoi faut-il limiter les fonctionnalités d'un compte non-connecté?

**Comment by nondidju** [comment]
J'ai l'impression qu'on peut passer beaucoup de temps à développer des fonctionnalités pour les non-logués. Alors que si quelqu'un se sent suffisamment investi par le site pour rapporter un point, il prendra la peine de se créer un compte. Les possibilités seront plus larges par la suite avec une page "utilisateur" faisant l'historique des points relevés, un formulaire de contact,...

On peut aussi travailler sur la facilité de se créer un compte avec le nouveau Persona de Mozilla.

**Comment by julienfastre** [comment]
Pour ma part, je propose que l'on poursuive avec la décision déjà prises: seuls les gens enregistré peuvent enregistrer des photos.

Pour moi, c'est moins une question d'inciter aux gens à se créer un compte plutôt qu'une question d'utilisation des ressources: uploader des photos prend de la place sur le serveur; et ça risque d'encombrer rapidement nos serveurs. 

Pouvoir envoyer des photos en étant non connecté pourrait également être un moyen d'attaque assez simple (faire un script qui envoie x photos en une nuit; le lendemain à notre réveil on doit tout nettoyer)

Au moins, lorsque les utilisateurs sont connectés, on peut savoir qui a envoyé quoi et suivre les envois des utilisateurs. 

De même, si quelqu'un envoie des photographies délictueuses, on pourra mieux retracer sa provenance et le suivre - même s'il change d'adresse IP.
