### ISSUE TITLE
Notifications dans la page, pas en pop-up

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#55]

**Comment by julienfastre** [comment]
Au fait, on pourrait utiliser un seul endroit pour les notifications, qui soit le même lorsque j'envoie des messages depuis le serveur. Ca serait plus simple pour la mise en forme. Pourquoi ne pas utiliser la div flash-notice ? https://github.com/progracqteur/WikiPedale/blob/master/src/Progracqteur/WikipedaleBundle/Resources/views/layout.html.twig#L71 (ligne 71)

On pourrait faire un script qui "enlève" le message après une minute, par exemple, pour garder la page "propre".

**Comment by marcu** [comment]
ça me semble plus lisible si les messages relatifs à un formulaire soient
dans le formulaire du coup j'ai l'impression que c'est bien comme c'est
maintenant.

2013/1/7 Julien Fastré notifications@github.com

> Au fait, on pourrait utiliser un seul endroit pour les notifications, qui
> soit le même lorsque j'envoie des messages depuis le serveur. Ca serait
> plus simple pour la mise en forme. Pourquoi ne pas utiliser la div
> flash-notice ?
> https://github.com/progracqteur/WikiPedale/blob/master/src/Progracqteur/WikipedaleBundle/Resources/views/layout.html.twig#L71(ligne 71)
> 
> On pourrait faire un script qui "enlève" le message après une minute, par
> exemple, pour garder la page "propre".
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/progracqteur/WikiPedale/issues/55#issuecomment-11950237.

## 

et en avant pour de folles aventures...

**Comment by julienfastre** [comment]
ok.
