### ISSUE TITLE
Pouvoir accéder directement à un point noir

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#58]
[edit 22/10/2012] La route est à modifier par @julienfastre et le JS est également à faire.

**Comment by julienfastre** [comment]
J'ai réalisé le code en php (bc230ca60ed644dbf112d1c2e9af0dd4f3ab9501): 

Lors d'une requête vers /?id=xx (soit la homepage avec un paramètre id, où le numéro d'id correspond à une numéro d'id d'emplacement existant), la ville correspondant à cet id est automatiquement sélectionnée et considérée comme la ville "de travail" de l'utilisateur.

Puis, de manière classique, la homepage est renvoyée et l'utilisateur n'a plus qu'à travailler. 

Il reste à écrire le code javascript pour que l'emplacement s'affiche dans la colonne de droite. Je change donc l'assignation à @marcu .

**Comment by marcu** [comment]
par ex pour : app_dev.php/?id=1580

il faut exécuter la fonction displayPlaceDataFunction(markers_and_associated_data[1580][0],markers_and_associated_data[1580][1]); au bon moment (synchroniser le JS)

mais comment l'id est reçu dans le js/html? comment est on au courant qu'il faut afficher ce point là?

**Comment by julienfastre** [comment]
Voilà, peux-tu regarder si c'est bon pour toi ?

**Comment by marcu** [comment]
oui ça marche. merci. c'est fini.

**Comment by marcu** [comment]
oui ça marche. merci

On 21 December 2012 22:32, Julien Fastré notifications@github.com wrote:

> Voilà, peux-tu regarder si ça fonctionne ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/progracqteur/WikiPedale/issues/58#issuecomment-11627715.

## 

et en avant pour de folles aventures...
