### ISSUE TITLE
Nom des villes avec majuscule, accents, (stockage dans les paramètres de session)

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#6]
Pour la locale "Ottignies/Louvain-la-Neuve" ont veut avoir à ce nom dans twig via {{ app.session.get('city') }}.

Il faudrait un fichier (ou dans base de donnée) qui associe chaque URL avec le nom dans le format de publication.

**Comment by julienfastre** [comment]
Ok pour moi. 

Je corrige le titre pour préciser que ça ne concerne pas les URL.
