### ISSUE TITLE
Recherche des derniers emplacements créé depuis une date x

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#62]

**Comment by julienfastre** [comment]
Avec les notifications, est-ce encore pertinent ?

**Comment by marcu** [comment]
pour quelqu'un qui n'est pas abonné aux notifications ça peut-être intéressant. mais ça ne me semble pas apporter beaucoup à l'outil.

**Comment by julienfastre** [comment]
Ok, on ferme cette issue, quitte à la réouvrir plus tard.
