### ISSUE TITLE
Pbm lors de l'enregistrement

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#67]
Après complétion du formulaire erreur "Connection could not be established with host localhost [Connection refused # 61] "

**Comment by julienfastre** [comment]
Ca, ça ressemble plus à une erreur du serveur local: la connexion avec la base de donnée ne doit pas être localhost mais l'adresse IP du serveur de BD (que je préfère ne pas publier sur internet :-) )

**Comment by julienfastre** [comment]
Et en version de test (wikipedale.fastre.info) ça fonctionne: il doit donc s'agir d'un problème en lien avec la connexion que tu as utilisée.

**Comment by marcu** [comment]
ok mais la db marche sans problème pour l'affichage des points noirs.

sur fastre.info j'ai aussi une erreur : 

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please e-mail us at [email] and let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 

Mes paramètres : 
- login : blop
- mail : marc@blop.com
- pwd : blop
- verif : blop

**Comment by julienfastre** [comment]
Ha ok je viens de comprendre qu'il s'agissait de l'enregistrement d'un utilisateur!

(heu, c'est bien ça?)

Il faut régler les paramètres smtp dans parameters.ini : ça envoie un email à celui qui s'enregistre. Il faut qu'ils soient corrects.

Pour fastre.info je suis au courant et pas pu régler encore.

**Comment by marcu** [comment]
oui c'est bien l'enregistrement d'un utilisateur!

**Comment by julienfastre** [comment]
Est-ce que ça fonctionne lorsque parameters.ini est configuré correctement ? 

On peut fermer l'issue ?

Sur wikipedale.fastre.info, ça a été corrigé.

**Comment by julienfastre** [comment]
Je ferme, j'imagine que ça a été réglé.
