### ISSUE TITLE
Lien "Créer un compte" à changer si l'utilisateur est connecté

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#69]
Il faut changer le lien "créer un compte" en "Déconnexion"

**Comment by julienfastre** [comment]
Fait en php : 3adc0e6b54cd7a4688e93d335f105b8b76876637

J'ai ajouté également un lien vers "votre profil".

Attention il faudra changer les liens quand l'utilisateur est connecté. Je ne ferme donc pas cette issue mais l'assigne à @marcu pour la suite.

**Comment by julienfastre** [comment]
Voir aussi #75
