### ISSUE TITLE
Nom des villes case-insensitve

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#7]
pouvoir accéder à la page de liège via :
- app_dev.php/Liege
- app_dev.php/liege
- app_dev.php/LIEGE

**Comment by julienfastre** [comment]
Ok, je vais le faire. 

A mon avis, on pourrait aussi tenter de récupérer les accents (Liège, Liége, etc.) . Pour "Lièche", c'est plus difficile.

Mais si la variable est détectée avec ses différentes formes orthographiques, je propose qu'une forme normalisée soit affiché par la suite : 

Liège => liege
Mons => mons
Ottignies Louvain-la-Neuve => ottignies_louvain_la-neuve
La Louvière => la_louviere

etc.

**Comment by marcu** [comment]
Oui il faut une forme normalisée

**Comment by julienfastre** [comment]
Les noms des villes et leurs limites géographiques sont maintenant dans la base de donnée. 

Je l'ai pré-remplie avec les communes de Wallonie.

Il faudra peut-être adapter le positionnement du centre des communes. Pour l'instant, le système a calculé automatiquement le "centroid", mais ça n'est peut-être pas le meilleur endroit pour l'affichage (http://postgis.refractions.net/documentation/manual-2.0/ST_Centroid.html). Des ajustements manuels pourront avoir lieu. 

Il n'est pas prévu de pouvoir modifier ces informations par une interface web (les limites de communes risquent peu de changer). Il faudra donc intervenir directement sur la base de donnée. 

De même, pour l'instant, les noms de commune sont en majuscule: il faudra prendre du temps pour les remettre en minuscule, ajouter les accents, etc. 

Pour ces deux éléments, je suggère de faire ça dans la BD de production - sinon on risque de devoir recommencer à chaque fois que je recrée la base pour les besoins du développement.

Il me reste à développer une fonction qui normalisera le nom de la ville en une forme normalisée (slug) dans les requetes (il est déjà prêt dans la BD).

**Comment by julienfastre** [comment]
Introduire un nom de ville avec des caractères accentués, ou non, majuscule ou non, renvoie vers la ville normalement recherchée. (a9d84741d0befd9519bf01d066459c2e1e300e17)
