### ISSUE TITLE
Connection ne fonctionne pas sur la page "choisir une ville"

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#70]

**Comment by julienfastre** [comment]
Je pense qu'il faut mettre le code javascript nécessaire sur la page de choix des villes. Sinon, bien entendu, le formulaire de connexion ne s'ouvrira pas.

**Comment by marcu** [comment]
fait mais le Default/homepage.html.twig semble un peu chargé. Ne faut-il pas le diviser en 2? Un quand l'utilisateur choisit une ville et un autre qd une ville est choisie et modification/ajout des points noirs.

**Comment by julienfastre** [comment]
Bonjour,

Je me demande aussi s'il ne faudrait pas simplifier cette page, et déplacer le template twig "choix d'une ville" vers un autre fichier.

J'ai mis un commentaire sur une ligne: https://github.com/progracqteur/WikiPedale/commit/ad8b62aca3030cf35663c5c4cc6f4638d8babd5b#commitcomment-2099259

Pour le formulaire de connexion: ne serait-ce pas plus simple de mettre le code de connexion dans le template de layout général (https://github.com/progracqteur/WikiPedale/blob/master/src/Progracqteur/WikipedaleBundle/Resources/views/layout.html.twig), plutôt que de le répéter sur chaque page ?
