### ISSUE TITLE
Différence de couleur bordure du formulaire "ajouter un point" et bouton "annuler" (l'ajout de point) avec :hover

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#78]
Il y a une légère différence de couleur entre le rouge de la bordure du bouton "ajouter un point" et le rouge clair du bouton "annuler" lorsque on survole le bouton avec la souris. 

Ca me donne l'impression que les frontières ne sont pas très bien définies entre les deux.

Je me demandais s'il n'y avait pas moyen de corriger ça: soit les espacer, soit modifier également la couleur de la bordure (mais uniquement au survol du bouton "annuler"), soit... [autre solution à inventer]

Mais c'est vraiment minime comme détail :-)

**Comment by nondidju** [comment]
Cette différence de couleur est là pour justifier le lien et l'action, moi elle ne me dérange pas. Par contre, je me dis que ce lien n'est pas très explicite, il vaudrait peut-être mieux faire référence à des éléments plus habituels tel qu'une croix en haut à droite ou un bouton "annuler" à côté du bouton "envoyer" (ou les deux).
