### ISSUE TITLE
Ajout d'une adresse (rue, numéro, CP, Ville) dans la définition des emplacements

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#8]

**Comment by julienfastre** [comment]
Nulle part, donc j'ai modifié le titre du thread... 

Question: faut-il installer la recherche de l'adresse côté serveur, ou cela peut-il être fait côté client ? (voir le service Nominatim de mapquest, par exemple).

**Comment by marcu** [comment]
ok nominatim ça me semble bien. je vais travailler un peu de ce coté!

2012/6/6 Fastré
reply@reply.github.com:

> Nulle part, donc j'ai modifié le titre du thread...
> 
> Question: faut-il installer la recherche de l'adresse côté serveur, ou cela peut-il être fait côté client ? (voir le service Nominatim de mapquest, par exemple).

**Comment by julienfastre** [comment]
Pourras-tu faire des appels javascript directement ou faudra-t-il bidouiller qqch côté serveur ? (je pense à la règle du 'same origin policy' https://en.wikipedia.org/wiki/Same_origin_policy )

Mapquest a mis en place un service nominatim que l'on pourrait utiliser http://developer.mapquest.com/web/products/open/nominatim et http://open.mapquestapi.com/nominatim/ . Il faudra les créditer, cependant. 

Pour la structuration JSON, j'avais l'idée d'utiliser la même structure que l'objet address récolté par cette requete : http://open.mapquestapi.com/nominatim/v1/reverse?format=json&lat=50.644753&lon=5.555795

**Comment by marcu** [comment]
faisons au plus simple : utilisons celui de mapquest ou celui
d'openstreetmap (mais il est limité). non?

2012/6/7 Fastré
reply@reply.github.com:

> Pourras-tu faire des appels javascript directement ou faudra-t-il bidouiller qqch côté serveur ? (je pense à la règle du 'same origin policy' https://en.wikipedia.org/wiki/Same_origin_policy )
> 
> Mapquest a mis en place un service nominatim que l'on pourrait utiliser http://developer.mapquest.com/web/products/open/nominatim et http://open.mapquestapi.com/nominatim/ . Il faudra les créditer, cependant.
> 
> Pour la structuration JSON, j'avais l'idée d'utiliser la même structure que l'objet address récolté par cette requete : http://open.mapquestapi.com/nominatim/v1/reverse?format=json&lat=50.644753&lon=5.555795
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/progracqteur/WikiPedale/issues/8#issuecomment-6186874

## 

et en avant pour de folles aventures...

**Comment by marcu** [comment]
au fait un exemple pour le nominatim d'openstreetmap (mais il y a une
limite mais je crois qu'on sera en dessous) :

http://jsfiddle.net/GWL7A/14/

2012/6/11 Marc Ducobu marc.ducobu@gmail.com:

> faisons au plus simple : utilisons celui de mapquest ou celui
> d'openstreetmap (mais il est limité). non?
> 
> 2012/6/7 Fastré
> reply@reply.github.com:
> 
> > Pourras-tu faire des appels javascript directement ou faudra-t-il bidouiller qqch côté serveur ? (je pense à la règle du 'same origin policy' https://en.wikipedia.org/wiki/Same_origin_policy )
> > 
> > Mapquest a mis en place un service nominatim que l'on pourrait utiliser http://developer.mapquest.com/web/products/open/nominatim et http://open.mapquestapi.com/nominatim/ . Il faudra les créditer, cependant.
> > 
> > Pour la structuration JSON, j'avais l'idée d'utiliser la même structure que l'objet address récolté par cette requete : http://open.mapquestapi.com/nominatim/v1/reverse?format=json&lat=50.644753&lon=5.555795
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/progracqteur/WikiPedale/issues/8#issuecomment-6186874
> 
> ## 
> 
> et en avant pour de folles aventures...

## 

et en avant pour de folles aventures...

**Comment by julienfastre** [comment]
Les adresses apparaissent maintenant lors de la transformation en json. 

Une question : si un élément est vide (par exemple, la rue), doit-il apparaître ? Doit-il s'agir d'une chaine vide ou de la valeur null ?

**Comment by marcu** [comment]
une chaine vide (c'est comme ça que ça va se trouver dans la db).

**Comment by julienfastre** [comment]
Les adresses sont maintenant effectives.

Certaines informations sont reprises de Nominatim et ne sont peut-être pas utiles ('administrative', 'county_code', etc.). A voir si on conserve. C'est pas très compliqué d'ajouter ou d'enlever des éléments.

**Comment by marcu** [comment]
pour moi il ne faut qu'un champ adresse (actuellement appelé lieu) :
- qui est remplit automatiquement quand on clique sur la carte en fct de la rue la plus probable
- l'utilisateur peut modifier l'adresse si il veut 
  n'est-ce pas plus simple?

**Comment by marcu** [comment]
je vois que les champs sont : 
- "city":"Mons",
- "administrative":"",
- "country_code":"",
- "county":"Hainaut",
- "state":"R\u00e9gion wallonne",
- "state_district_declaration":"",
- "road":"",
- "public_building":""
  à part la "road" on n'a besoin de rien vu qu'on a le long/lat.

**Comment by julienfastre** [comment]
Pour la manière d'utiliser le champ d'adresse, je suis d'accord. 

J'ai limité le nombre de champs à celui de la route (74d885b1e42e2239a061d2edc985291e63ed111b)
