### ISSUE TITLE
[formulaire ajout point] retirer le login / email si l'utilisateur est déjà connecté

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#81]
Pour moi, si l'utilisateur est déjà connecté, on ne doit pas leur demander de re-remplir leur login/ adresse mail. 

Pourquoi ? Par cohérence et clarté: on ne va pas leur proposer de remplir un champ qu'ils n'auront pas à remplir alors que, de plus, s'ils parvenaient à le modifier leurs changements ne seraient pas pris en compte côté serveur.

**Comment by marcu** [comment]
Mais actuellement le formulaire est pré-rempli et il ne peut pas être
modifié

2012/12/18 Julien Fastré notifications@github.com

> Pour moi, si l'utilisateur est déjà connecté, on ne doit pas leur demander
> de re-remplir leur login/ adresse mail.
> 
> Pourquoi ? Par cohérence et clarté: on ne va pas leur proposer de remplir
> un champ qu'ils n'auront pas à remplir alors que, de plus, s'ils
> parvenaient à le modifier leurs changements ne seraient pas pris en compte
> côté serveur.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/progracqteur/WikiPedale/issues/81.

## 

et en avant pour de folles aventures...

**Comment by julienfastre** [comment]
Oui, c'est vrai.... Et justement, vu qu'on ne sait pas le modifier et qu'on a dû faire une action sur les input, je me demande pourquoi ne pas les enlever purement et simplement... je trouve ça plus clair.

**Comment by julienfastre** [comment]
Super  ! :-)

**Comment by julienfastre** [comment]
Apparemement, quelque chose a dû se casser, parce que le login et email restent apparents à nouveau. Je le réouvre comme un bug.

**Comment by julienfastre** [comment]
Résolu par #92
