### ISSUE TITLE
Réponse lors d'un login

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#82]
Quand le formulaire n'est pas rempli il n'y a pas d'erreur et le JSON renvoyé est 
{"query":{"error":false,"nb":1,"start":0},"results":[null]}

Quand le formulaire est rempli mais pas bon nom d'utilisateur on reçoit une erreur 403

Il faudrait unifier les deux.

**Comment by julienfastre** [comment]
En fait, j'avais suivi une certaine logique lorsque j'avais suivi ces deux comportements différents : 
- une authentification en WSSE est possible vers n'importe quelle URL; c'est un comportement simple pour les autres clients (appli android): ils n'auront pas à stocker un cookie ou un identifiant de session: ils enverront un header X-WSSE et pourront exécuter toutes les requêtes nécessaires et ne devront pas effectuer une requête d'authentification au préalable ;
- l'action /authenticate.json est là juste pour vérifier une authentification. Il permet de récupérer l'user logué, qu'il se soit logué lors de la requête courante avec wsse ou avec une autre méthode. Il est donc logique que la réponse soit `null` si aucun user n'est logué ;
- par contre, si des données de connexion sont fausses, il est logique d'avoir une erreur 403, qui indique une erreur dans la connexion (http://fr.wikipedia.org/wiki/Liste_des_codes_HTTP)

Ce que je propose: que l'on ajoute l'attribute `required` aux input du formulaire  de connexion (login et mot de passe), voire que l'on impose, par un attribut pattern="//quelque chose à trouver" un minimum de trois caractères (je pense qu'il vaut mieux passer par les nouveaux attributs HTML5 que de composer du code javascript de vérification).  cf http://www.w3schools.com/html5/att_input_required.asp et http://www.w3schools.com/tags/tag_input.asp)

**Comment by marcu** [comment]
safari ne gère pas "required" : http://caniuse.com/#feat=form-validation et http://www.w3schools.com/tags/att_input_required.asp.

je vais vérifier à la main si le formulaire n'est pas nul.

**Comment by julienfastre** [comment]
Ok. 

Dommage pour Safari.

**Comment by julienfastre** [comment]
Doit-on modifier le comportement côté serveur ? Dans la réponse, j'en déduis que non. Donc je ferme l'issue, mais si je me trompe, n'hésitez pas à la réouvrir.
