### ISSUE TITLE
[codage html] Mettre le code js dans les  balises head

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#83]
Je vois que du code `<script>...</script>` apparait dans le code html, sur la homepage (https://github.com/progracqteur/WikiPedale/blob/master/src/Progracqteur/WikipedaleBundle/Resources/views/Default/homepage.html.twig)

Ne serait-il pas mieux de le placer dans les balises header ? 

Il y a un block `javascript` qui est disponible pour cela dans le layout (https://github.com/progracqteur/WikiPedale/blob/master/src/Progracqteur/WikipedaleBundle/Resources/views/layout.html.twig). Il suffit de faire:

```
{% block javascript %}

<!-- mettre le code ici -->
<script>...</script>

{% endblock %}
```

et ça sera ajouté dans le header.

**Comment by marcu** [comment]
j'ai un peut travaillé ça ce soir.

sinon on avait dit qu'on allait séparer la page d'acceuil (choix de la ville) avec celle où la carte est affichée. as tu un idée? ou de la doc à me conseiller?

merci

**Comment by julienfastre** [comment]
Je pense que le plus propre (mais c'est à discuter) est de créer deux templates Twig: l'un qui est utilisé dans la page d'accueil, l'autre pour la page d'édition principale. 

Le contrôleur sélectionnera l'un ou l'autre en fonction de ce que demande l'utilisateur. 

Après, comme discuté hier au téléphone, il peut encore y avoir des sous-templates si nécessaires, pour certaines parties du twig (comme les formulaires, etc.). Twig peut appeler des sous-templates [voir ici](http://twig.sensiolabs.org/doc/templates.html#including-other-templates).

**Comment by julienfastre** [comment]
Je pense qu'on peut fermer cette issue, non ?
