### ISSUE TITLE
Créer un système de catégorisation des points

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#85]
(voir aussi issue #20)

**Comment by julienfastre** [comment]
Le système de catégorie est presque prêt (voir 12ac1f842a4ccc16c653de7de7a0ad249d81b6ef et ec9b168f8e0c27e355b0402eafeaab770a1b8b67)

Conformément à une conversation téléphonique qui a eu lieu avec Marc, j'ai créé un système qui permet d'avoir une catégorie parente et une sous-catégorie. Il y a donc une hiérarchie à deux niveaux. 

Les catégories peuvent être gérées par une interface d'administration. Seules les personnes ayant le rôle d'admin y ont accès. 

J'ai déjà ajouté des catégories "test" en [m'inspirant du formulaire du GRACQ](http://www.gracq.be/LOCALE-Nivelles/Signalement).

Chaque catégorie a: 
- un id (un entier)
- un label (en français, pas d'internationalisation prévue pour cet élément) (255 caractères maximum)
- zéro ou une catégorie parente

Les catégories parentes sont gérées par la même interface graphiques ; elles sont stockées dans la même table ( @marcu : il était plus simple et il m'apparaissait plus propre de ne créer qu'une seule classe, formulaire, etc.; il y a des outils suffisant pour éviter les hiérarchies de catégories).

Pour l'instant, il est prévu que l'on puisse ajouter plusieurs catégories à un signalement: il s'agit d'une relation many-to-many entre les catégories et les emplacements. 

Notez que la base de donnée a été modifiée lors des deux commits cités plus haut.

Il reste à faire : 
- la validation : 
  - (vérifier que le texte du label n'ait que 255 caractères (sinon erreur dans la db)
  - vérifier que la catégorie parente ne soit pas une catégorie fille d'une autre (sinon on a des hiérarchies multiples)
- comment les représenter en JSON ? J'avais pensé à ceci :

``` json
{
    "entity":"place"
   /* .... */
    "catégories": [
          {
                 "entity":"category"
                 "id":25,
                 "label":"mauvais revetement",
                 "parent": {"entity":"category","id":20","label":"Revements"}
            }
     ]
}
```

Qu'en pensez-vous ?

Faut-il un endroit où toutes les catégories sont affichées/disponibles pour le JS ?

**Comment by julienfastre** [comment]
Autre question: pourrait-on associer aux emplacements une catégorie "parente" ? Autrement dit, une catégorie qui a des filles "sous" elle ?

**Comment by marcu** [comment]
Proposes tu cette possibilité au cas où aucune sous-catégorie ne fonctionne? si oui ne vaut-il mieux ne pas mettre une sous-catégorie autre?

**Comment by julienfastre** [comment]
S'il faut prévoir une catégorie "autre", alors c'est à l'administrateur de la prévoir et on peut bloquer l'association de catégories parentes (ou alors seulement certaines catégories) à un signalement.

Le tout est de savoir si le système doit accepter ou pas qu'une catégorie parente soit associée à un signalement. 

Mais bon, on peut peut-être laisser aller, et voir par la suite...

**Comment by julienfastre** [comment]
Les catégories sont désormais affichées dans le json des emplacements (7a777ad87bebeb18885b270fc93f165f1f3f4509)

Dcoumentation dans le wiki suivra.

**Comment by julienfastre** [comment]
Il ne reste plus qu'à tenir compte des catégories dans la validation des modifications côté serveur. 

Les requêtes en json d'ajout ou de retrait des catégories fonctionnent.

J'ai ajouté la documentation dans le wiki hier.

**Comment by julienfastre** [comment]
Je pense qu'il ne reste plus qu'à vérifier qu'il soit impossible d'ajouter une catégorie "parente" à l'emplacement.

**Comment by julienfastre** [comment]
J'ai adapté le système des catégories: il est maintenant possible d'avoir trois niveaux de catégories (petit | gros | moyens problèmes < categorie parente < categorie fille). 

Mais je pense qu'on va se casser les dents sur l'affichage des catégories et des catégories parentes, la validation, le choix des catégories possibles, etc. 

Par exemple: le problème des revêtements inadaptés est un "gros" point noir, un trou dans la route est un "moyen" ou un "petit" problème. Comment va-t-on l'afficher ? L'utilisateur va-t-il vérifier dans toutes la hiérarchie ? 

Pour moi : 
- soit on fixe qu'il faut toujours trois niveaux de catégories (et alors il faut toujours inventer une hiérarchie à trois niveaux qui soit facile à utiliser, ça me parait difficile en soi) ;
- soit on en revient deux niveaux de catégories, et le petit/gros/moyen problème devient un paramètre de la catégorie (plus simple également pour les utilisateurs).
