### ISSUE TITLE
Associer les signalements à des gestionnaires de voirie

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#86]
Lors de leur introduction, les signalements seront notifiés aux gestionnaires de voirie. 

L'association d'un signalement à un gestionnaire de voirie suivra l'algorithme suivant:

Pour le gestionnaire de voirie, je pense que l'on pourrait parvenir à trouver qui est le gestionnaire ad hoc à partir des éléments suivants :
- si un signalement est fait à moins de 5-10m d'une voirie régionale, il sera associé à la route régionale (fichiers géographiques des routes régionales nécessaires)
  - dans ce cas, on enverra une notification à la personne de contact du district (limites géographiques des districts nécessaires)
- sinon, ça sera envoyé à la commune (limites des communes nécessaire)

**Comment by marcu** [comment]
pour moi c'est du coté serveur que ça doit être géré mais ce n'est pas si simple.

je ne vois qu'une solution possible : faire appel à un serveur openstreetmap qui renvoie le contenu de la région 5-10m autour du point et analyser cette région ; ça doit se faire du coté serveur. avez-vous d'autres solutions?

**Comment by julienfastre** [comment]
Voilà comment j'ai imaginé l'implémentation de cette fonction : 
- on va créer des "groupes" de gestionnaires de voirie. Chaque utilisateur pourra faire partie de zéro à x groupe de gestionnaire ;
- chaque groupe sera associé à des zones géographiques : au moins un polygone (les limites de commune ou de district du SPW) et éventuellement des lignes (les routes).
- je vais créer un service qui se chargera d'associer les points à un groupe de gestionnaire. Ce service : 
  - pourra être activé ou désactivé dans les paramètres : cela permettra la personnalisation du logiciel pour d'autres zones (ce que l'on vise, ça n'est pas l'implémentation pour la wallonie, mais pour le monde entier). S'il est activé, il pourra être personnalisé également dans les paramètres (concrètement, il faudra mettre un paramètre dans le fichier app/config.yml)
  - il sera appelé à chaque fois qu'un point est créé, ou qu'un point est déplacé (modification du paramètre geom).

Pour déterminer qui est gestionnaire de la voirie, je pense qu'il faut utiliser des données de la région : les données d'OSM ne stockent pas l'opérateur des routes (le tag operator est quasi vide en belgique : cherchez ici pour l'opérator SPW : http://taginfo.openstreetmap.org/keys/?key=operator#values ) . Je vais demander à Luc qui pourrait nous fournir ça. 

J'intégrerai les données directement dans la BD, il n'y aura pas d'interface graphique pour les modifier. Par contre je serai attentif à ce qu'il soit possible de les mettre à jour (on ne sait jamais) ou d'ajouter des couches (gestionnaires privés, etc.)

Pour la Wallonie, je propose que l'on fasse comme ceci : 
- si le point est à moins de 5-10 m d'une route régionale, le point sera associé à un gestionnaire régional
  - le système cherchera alors dans quel district se trouve le point et sélectionnera ce district comme gestionnaire ;
- sinon, ça ira aux communes.

Voilà où j'en suis dans mes réflexions. Si vous avez des idées...

Effectivement, tout se passera côté serveur.

**Comment by julienfastre** [comment]
Ajoutons également que le gestionnaire de voirie devra pouvoir être modifié manuellement par les personnes ayant le rôle d'administration du site.

**Comment by julienfastre** [comment]
A faire : 
- [x] Ajout données dans BD et classe
- [x] script de vérification des droits
- [x] Modification de la normalisation en json, avec normalisation des groupes
- [x] Validation du type de groupe
- [x] Ajout des groupes dans le jeu de données test
