### ISSUE TITLE
carte à intégrer dans autres siteweb

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#9]
Dans le même ordre d'idée de diffusion, ne serait-il pas intéressant de permettre l'intégration facile de cette carte dans un autre site web ? Ce pourrait être par exemple sans permettre de modifier, juste visualiser. Idem prévoir les boutons pour réseaux sociaux, j'aime, partager etc.

par maxime de liège

**Comment by julienfastre** [comment]
+1 pour moi avec une condition : pour les boutons "réseaux sociaux", je pense qu'il faut éviter les boutons qui permettent à Facebook, Google, etc. de 'tracker' les utilisateurs (même s'ils ne sont pas connectés). Il faudrait donc voir s'il existe un système qui ne télécharge pas des scripts sur leur site tant que l'utilisateur n'a pas cliqué sur "j'aime" ou "partager". 

(En effet, en utilisant le module de Firefox "Collusion", on peut se rendre compte à quel point nos visites sont épiées par les majors, qui sont capables de les retracer lorsque le site en question héberge un bouton venant de leur propre site)
