### ISSUE TITLE
[formulaire de signalement]Remise à zéro du formulaire après un signalement 

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#92]
Après un signalement réussi, il semble que le formulaire ne se remet pas à zéro: les catégories restent indiquée, le message "le signalement a été enregistré" continue de s'afficher, etc.

Je pense qu'avant, le formulaire se remettait à zéro (ou je me trompe ?).

**Comment by marcu** [comment]
le problème vient du fait que l'élément ayant l'id "form_informer_description" a été supprimé -> d'où le js lance une erreur et arrête de s'exécuter.
