### ISSUE TITLE
Créer les différents rôles et groupes utilisateurs

### ISSUE THREAD

**Issue by julienfastre** [progracqteur/WikiPedale#93]
Les rôles seront les suivants : 
- modérateur (ROLE_MODERATOR)
- gestionnarie de voirie (ROLE_MANAGER)
- notation (pour pouvoir attribuer une notation)

![Capture du 2013-02-05 21:15:45](https://f.cloud.github.com/assets/345600/129117/ee879296-6fd0-11e2-887f-b5d8fdb3fdce.png)

**Comment by marcu** [comment]
Je crois qu'il faut aussi déjà penser aux rôles pour la gestion des gros points noirs.

Il faudrait qqchose du genre :
- ROLE_MODERATOR_BIG (pour modérer les gros points)
- ROLE_MANAGER_C1_BIG (pour changer la couleur "c1" pour les gros points)

**Comment by julienfastre** [comment]
Ok pour la remarque ci-dessus. 

Je vais également modifier séparer le type de groupe et les rôles, pour que ça soit (j'espère ;-) ) plus clair. 
- les types de groupe sont la fonction définies dans le système: le modérateur, gestionnaire de voirie, modérateur GRACQ, notation, etc; 
- les rôles sont les droits: le droit de modifier les catégories (ROLE_CATEGORY), le droit de modifier le gestionnaire de voirie (ROLE_ALTER_MANAGER), le droit d'ajouter des commentaires "confidentiels", etc.

Pourquoi séparer les deux ? Parce que certains droits seront partagés entre deux types de groupes. 

Par exemple, le modérateur "conseiller en mobilité" pourra changer la notation (donc la couleur) qui lui est désignée. Tout comme le groupe "modérateur de point noir" GRACQ (mais il aura une autre notation qui lui est désignée). Il y a d'autres exemples de types de groupes où les droits se rejoignent. 

Au moment de vérifier les droits, cela devrait être plus simple: au moment où les groupes sont créés, les droits sont assignés à chaque groupe en fonction du type de groupe. Et au moment de vérifier qu'un utilisateur a bien le droit de faire ce qu'il fait, il n'y a qu'à faire appel à la fonction suivante : `$userToken->isGranted('ROLE_A_VERIFIER)` (dans le cas où on doit vérifier les types, cela oblige à faire `$userToken->getUser()->getType() == 'TYPE' OR $userToken->getUser()->getType() == 'UN_AUTRE_TYPE'` - et, de plus, si on modifie quelque chose, il faudra repasse tout le code en revue !)

**Comment by julienfastre** [comment]
Je pense avoir implémenté suffisamment pour le milestone 1.1.
