### ISSUE TITLE
choix petits et gros points noirs

### ISSUE THREAD

**Issue by marcu** [progracqteur/WikiPedale#96]
Je viens de rajouter un formulaire (qui ne marche pas) pour choisir les petits et gros points noirs.

Plusieures questions me viennent à l'esprit :
- où faut-il placer ce formulaire
  - va-t-il devenir plus complexe ?
    - choix des categories
    - choix de la couleur affichée
    - ...
- peut afficher les petits et gros points noirs en même temps
  - si oui, le fait-on avec des pointeurs différents
  - il faut penser à :
    - les petits points noirs : 1 seule couleur
    - les gros : plusieurs

**Comment by julienfastre** [comment]
Pour ma part, j'avais imaginé un système d'onglets en haut de la colonne de droite, où on peut choisir "petits" et "gros" points. 

(attention qu'il faudra renommer "petits" et "gros"...)

Mais il va falloir aussi créer un formulaire de filtre des points, à partir des catégories, des dates de résolutions, de l'état x ou y, ... 

Pour ce formulaire, je pensais l'ajouter en dessous du bouton "ajouter". Il se développerait lorsqu'on cliquerait dessus.
